In [1]:
import pandas as pd

df = pd.read_json("../../datas/vps/detected.json", lines=True)

df.head(5)

,method,path,headers,uuid,peer,status,cookies,response_msg,timestamp,post_data
0,GET,/,"{'host': 'localhost', 'user-agent': 'curl/7.68...",64644ea7-b358-4208-9b28-e5aaad5e00de,"{'ip': '172.18.0.1', 'port': 53212}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-14 07:30:36.539037,NaN
1,GET,/,"{'host': '202.10.35.215', 'connection': 'keep-...",64644ea7-b358-4208-9b28-e5aaad5e00de,"{'ip': '180.248.32.210', 'port': 30702}",200,{'sess_uuid': '7ee68b0c-9f55-47e5-b872-078d30b...,"{'version': '0.6.0', 'response': {'message': {...",2025-06-14 07:31:01.702421,NaN
2,GET,/stylesheets/jquery/jquery-ui-1.11.0.css?15286...,"{'host': '202.10.35.215', 'connection': 'keep-...",64644ea7-b358-4208-9b28-e5aaad5e00de,"{'ip': '180.248.32.210', 'port': 30702}",200,{'sess_uuid': 'c3f38f1d-a1be-477a-8692-9369ce7...,"{'version': '0.6.0', 'response': {'message': {...",2025-06-14 07:31:01.860896,NaN
3,GET,/stylesheets/application.css?1528612569,"{'host': '202.10.35.215', 'connection': 'keep-...",64644ea7-b358-4208-9b28-e5aaad5e00de,"{'ip': '180.248.32.210', 'port': 30709}",200,{'sess_uuid': 'c3f38f1d-a1be-477a-8692-9369ce7...,"{'version': '0.6.0', 'response': {'message': {...",2025-06-14 07:31:02.008505,NaN
4,GET,/stylesheets/responsive.css?1528612569,"{'host': '202.10.35.215', 'connection': 'keep-...",64644ea7-b358-4208-9b28-e5aaad5e00de,"{'ip': '180.248.32.210', 'port': 8026}",200,{'sess_uuid': 'c3f38f1d-a1be-477a-8692-9369ce7...,"{'version': '0.6.0', 'response': {'message': {...",2025-06-14 07:31:02.020142,NaN

In [2]:
user_agents_matrix = []
tmp = []
sess_uuids_user_agents = {
  # "{sess_uuid}": []
}
sess_uuids = []

for _, row in df.iterrows():
  sess_uuid = row.get("cookies", {}).get("sess_uuid") or row.get("response_msg", {}).get("response", {}).get("message", {}).get("sess_uuid")
  user_agent = row.get("headers", {}).get("user-agent", "")

  if user_agent == None:
    continue

  if sess_uuid in sess_uuids:
    sess_uuids_user_agents[sess_uuid].append(user_agent)
  else:
    sess_uuids_user_agents[sess_uuid] = [user_agent]
    sess_uuids.append(sess_uuid)

user_agents_matrix = list(sess_uuids_user_agents.values())
# for paths in sess_uuids_user_agents.values():
#   user_agents_matrix.append(paths)

sess_uuids_user_agents
# user_agents_matrix
# print(len(user_agents_matrix), len(sess_uuids_paths.keys()))

{'806c8d58-b04f-4634-b107-34877af9d1d0': ['curl/7.68.0'],
 '7ee68b0c-9f55-47e5-b872-078d30b9116b': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36'],
 'c3f38f1d-a1be-477a-8692-9369ce7d2c44': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36'],
 'f278a7c1-0785-48d7-bf05-539b1f48cc0c': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36'],
 '35356d10-0d1c-47ab-b018-36f62dd2a08f': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36'],
 '1e975ea3-2f2c-4183-a4ca-7637ddbe1eec': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36'],
 '7c28e45f-7aaa-42fa-b44d-0216a25150ab': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36'],
 '47685c7c-17cb-4303-8a1e-5e99a9e1f9bd': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36'],
 '09e54ba6-8322-4a86-afa8-a01dc89cb59b': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36'],
 '98ea628e-45bf-4a62-a0ee-3fab57dbf91d': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36'],
 'fd70efc6-4bea-4488-9b48-259dedb17253': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36'],
 '832ea6af-7ac1-4971-b205-2028efaef538': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36'],
 'a32ff6ba-c480-4519-b91e-539517820571': ['Hello World/1.0'],
 '8de81429-7607-4d4f-b31c-5e03ff10e2bd': ['curl/7.68.0'],
 '997a2bbc-7e8a-4088-9fb5-05809cdcaf81': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 Edg/90.0.818.46'],
 'f7358105-0eb0-474a-ba3e-6266aca8f90a': ['Hello World/1.0',
  'Hello World/1.0'],
 '623bcb95-5794-42ea-86e6-b1af1a13158c': ['Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1'],
 'bbed53f4-35ef-4722-b8df-269a46a691f1': ['Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36',
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36',
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36',
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36'],
 '76b1da02-e6c1-4826-b881-a504aefb8f0b': ['Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1'],
 '3d120c94-fd09-4619-adcb-715466a1b85f': ['Mozilla/5.0 (compatible; CensysInspect/1.1; +https://about.censys.io/)',
  'Mozilla/5.0 (compatible; CensysInspect/1.1; +https://about.censys.io/)',
  'Mozilla/5.0 (compatible; CensysInspect/1.1; +https://about.censys.io/)',
  'Mozilla/5.0 (compatible; CensysInspect/1.1; +https://about.censys.io/)',
  'Mozilla/5.0 (compatible; CensysInspect/1.1; +https://about.censys.io/)',
  'Mozilla/5.0 (compatible; CensysInspect/1.1; +https://about.censys.io/)'],
 'c9f54414-6d3d-4ab0-84d9-b17a5bc56abe': ['Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1'],
 '67ad7734-1a0d-44c4-91fb-f5a95e0cb51f': ['Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1'],
 '4021c006-9db4-4278-af06-808ead00ba8f': ['Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1'],
 '28e88c97-5ccb-4526-8113-1d65eb3aa43b': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'],
 'df46768d-6cf6-4b4e-bc82-7cff4ca4a9c1': ['Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1'],
 'e6dc69dd-97c6-4a9d-a842-8a1802e8e0c5': ['curl/7.68.0'],
 '252b722b-5181-4089-a148-0e6c2eedee0d': ['Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1'],
 '5a619609-691d-485b-ba0c-4d7ce6d9e18a': ['Hello World/1.0',
  'Hello World/1.0'],
 'f629a009-4764-4dcf-9121-953912923945': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 Edg/90.0.818.46'],
 'cc4fde00-f118-490f-b158-2eab31ebdd6c': ['Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0'],
 '1d20892e-df9a-4816-949f-6416fa32a10a': ['Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1'],
 '10760847-7b34-4af7-b53e-1dc0562d21c0': ['Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1'],
 '356a10a8-c46b-4c4f-b990-5a87e9626ac2': ['Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1'],
 'd0f4dd71-e8c1-4e83-b0ae-0a578031fdb5': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 Edg/90.0.818.46'],
 '1face405-0fa0-40f4-acc5-33f957af9033': ['Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1'],
 '8d7db90d-79e6-4029-98f8-324c3d9a3ebb': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0'],
 '22f29eb6-221d-4870-8b83-fd04e7d5c30d': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0'],
 'ac8bf79c-726f-4aa0-8f12-61b3df10efe8': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0'],
 '7738d8a9-292a-4497-904a-7651efcd8f99': ['Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1'],
 'a0c8a814-cfc0-4668-bb7d-9c73356c8fbe': ['Hello World/1.0',
  'Hello World/1.0'],
 'c5b8cd87-50cd-4d14-93aa-b3389af9efe1': ['Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1'],
 '1df72535-5045-4145-a395-90c20d2c7c11': ['Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1'],
 '0ed39147-fed9-4179-82c4-4ff84f92531f': ['xfa1'],
 '047aa8f9-0d61-433b-8f59-f5f6f8daf6c3': ['Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1'],
 'c5dd7888-775b-47a9-a28c-f32584abf216': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 Edg/90.0.818.46'],
 '375ebac4-4589-42e5-be80-2a9a53f64a79': ['Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1'],
 '90fb3a1d-d449-409d-a2b4-f32e6ee3ebd5': ['Mozilla/5.0; Keydrop.io/1.0(onlyscans.com/about);',
  'Mozilla/5.0; Keydrop.io/1.0(onlyscans.com/about);'],
 '1500fa23-b233-4ab6-9e42-9506f8d9a8f5': ['Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1'],
 'a876e6c1-6364-4a9a-84e4-41c948ea098a': ['Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1'],
 'b4580408-1ae0-4a35-967f-8b76025da5f4': ['curl/7.68.0'],
 'fdfea6b2-7629-4525-b94e-994d0e1b4c02': ['Hello World/1.0',
  'Hello World/1.0'],
 'a1f02805-3232-478b-afc7-933f606700fe': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 Edg/90.0.818.46'],
 '8e4e6af6-8732-476a-b29f-d0a0d0fd7cf1': ['Mozilla/5.0 zgrab/0.x'],
 '8d8e54c9-574e-4ae1-8a1f-24cd557d6efc': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 Edg/90.0.818.46'],
 'ed57daaa-8e5a-4748-91bf-bf12f95605c3': ['Mozilla/5.0'],
 '4a1d05e4-7d48-4e60-a4b6-d68543ee6f4e': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.6778.140 Safari/537.36'],
 '1af6395b-05c0-49e9-a63d-31774b8cc443': ['curl/7.68.0'],
 'c8c7da1a-0809-4459-b070-f860ed4b6e90': ['Mozilla/5.0'],
 '5e63f4e3-72a3-4606-a7d7-607202abd111': ['Hello World/1.0',
  'Hello World/1.0'],
 '886bacbd-0835-41af-97fc-4077f5410d07': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 Edg/90.0.818.46'],
 'b72a5770-2033-454c-b116-3a58b0a0fb70': ['Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:32.0) Gecko/20100101 Firefox/32.0',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:32.0) Gecko/20100101 Firefox/32.0',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:32.0) Gecko/20100101 Firefox/32.0',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:32.0) Gecko/20100101 Firefox/32.0',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:32.0) Gecko/20100101 Firefox/32.0',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:32.0) Gecko/20100101 Firefox/32.0'],
 '4cc3e677-ae7f-4272-ac1e-e80e4a528a99': ['curl/7.68.0'],
 '788a58e6-faf9-4329-9c7e-0d6d3b6bb778': ['Hello World/1.0',
  'Hello World/1.0'],
 'a095275f-688e-4743-9df6-a56cc877f543': ['Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0'],
 'f8d5daeb-62a8-4332-9b88-3da8f0052d77': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 Edg/90.0.818.46'],
 '7aea6c15-f917-460b-ad42-c7226e11fb0f': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36'],
 '8fd1aabe-0fc9-4081-837c-6e44298b03ca': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36'],
 '7b7eff7e-0382-4f4f-a60b-f6e9c63fb508': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36'],
 'be507312-77b8-4192-a2ee-ada36d8d9a47': ['Mozilla/5.0 (iPad; CPU OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) CriOS/30.0.1599.12 Mobile/11A465 Safari/8536.25 (3B92C18B-D9DE-4CB7-A02A-22FD2AF17C8F)'],
 'e473dd7b-425b-4d0e-add0-2e0b94b987b3': ['Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:14.0) Gecko/20100101 Firefox/14.0.1'],
 '1f50e10a-909e-4aad-87ac-2e4ad69c4b78': ['curl/7.68.0'],
 '1c270e8f-15cc-4bed-af51-56c06398b164': ['Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1'],
 'f8712c2e-b44e-4f46-b720-6bfceef0830b': ['Hello World/1.0',
  'Hello World/1.0'],
 '2561401f-b324-4abc-b305-5f36bf9378d6': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 Edg/90.0.818.46'],
 'a051cb03-6c18-45fd-befb-0f540ab3e30f': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'],
 'd5ed6912-3978-4939-907a-ba7bc84a62ad': ['curl/7.68.0'],
 '55475a8b-364e-42f9-9637-d70f0e803c95': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 Edg/90.0.818.46'],
 '31bb5d74-0b1d-4d22-bd1c-3387e4d02925': ['Hello World/1.0'],
 'efda917b-8df0-4a67-a23f-226ce2d4142d': ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36'],

In [3]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, fpmax, fpgrowth

te = TransactionEncoder()
te_ary = te.fit(user_agents_matrix).transform(user_agents_matrix)
df = pd.DataFrame(te_ary, columns=te.columns_)

df

,"Expanse, a Palo Alto Networks company, searches across the global IPv4 space multiple times per day to identify customers&#39; presences on the Internet. If you would like to be excluded from our scans, please send IP addresses/domains to: scaninfo@paloaltonetworks.com",Go-http-client/1.1,Hello World/1.0,Mozilla/5.0,"Mozilla/5.0 (Linux; Android 8.0.0; SM-G930F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.89 Mobile Safari/537.36","Mozilla/5.0 (Linux; Android 9; SAMSUNG SM-G975U Build/PPR1.180610.011) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/9.4 Chrome/67.0.3396.87 Mobile Safari/537.36",Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:32.0) Gecko/20100101 Firefox/32.0,"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_0) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.56 Safari/535.11",...,Mozilla/5.0 zgrab/0.x,Mozilla/5.0; Keydrop.io/1.0(onlyscans.com/about);,Opera/9.10 (Windows NT 5.1; U; hu),Opera/9.64(Windows NT 5.1; U; en) Presto/2.1.1,curl/7.68.0,l9explore/1.2.2,l9tcpid/v1.1.0,python-requests/2.32.3,python-requests/2.32.4,xfa1
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
142,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
143,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
144,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
145,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [5]:
# frequent_itemsets = fpgrowth(df, min_support=0.3, use_colnames=True)
frequent_itemsets = fpgrowth(df, min_support=0.0005, use_colnames=True)
### alternatively:
#frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
#frequent_itemsets = fpmax(df, min_support=0.6, use_colnames=True)

frequent_itemsets

     support                                           itemsets
0   0.109589                                      (curl/7.68.0)
1   0.068493  (Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...
2   0.041096  (Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...
3   0.116438                                  (Hello World/1.0)
4   0.143836  (Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...
5   0.136986  (Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 lik...
6   0.006849  (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/5...
7   0.013699  (Mozilla/5.0 (compatible; CensysInspect/1.1; +...
8   0.006849  (Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...
9   0.013699  (Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71...
10  0.013699  (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:...
11  0.006849  (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:...
12  0.013699                                             (xfa1)
13  0.006849  (Mozilla/5.0; Keydrop.io/1.0(onlyscans.com/abo...
14  0.006849                            (Mozilla/5.0 zgrab/0.x)
15  0.013699                                      (Mozilla/5.0)
16  0.013699  (Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...
17  0.006849  (Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; ...
18  0.006849  (Mozilla/5.0 (iPad; CPU OS 7_0 like Mac OS X) ...
19  0.006849  (Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:14...
20  0.006849  (Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...
21  0.006849  (Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...
22  0.006849  (Expanse, a Palo Alto Networks company, search...
23  0.006849  (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_...
24  0.006849  (Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...
25  0.020548                                   (l9tcpid/v1.1.0)
26  0.020548                                  (l9explore/1.2.2)
27  0.006849                (Mozilla/5.0 (PLAYSTATION 3; 1.10))
28  0.006849  (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_2...
29  0.013699  (Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...
30  0.013699  (Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:13...
31  0.006849  (Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWeb...
32  0.006849  (Mozilla/5.0 (Linux; Android 8.0.0; SM-G930F) ...
33  0.006849                           (python-requests/2.32.4)
34  0.006849  (Mozilla/5.0 (Windows; U; Windows NT 6.1; en-U...
35  0.006849  (Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...
36  0.006849               (Opera/9.10 (Windows NT 5.1; U; hu))
37  0.006849   (Opera/9.64(Windows NT 5.1; U; en) Presto/2.1.1)
38  0.006849  (Mozilla/5.0 (Windows; U; Windows NT 5.1; en-G...
39  0.006849  (Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebK...
40  0.006849  (Mozilla/5.0 (Windows; U; Windows NT 6.1; en; ...
41  0.006849  (Mozilla/5.0 (Windows NT 6.2; Win64; x64) Appl...
42  0.006849  (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:...
43  0.006849  (Mozilla/5.0 (Linux; Android 9; SAMSUNG SM-G97...
44  0.006849  (Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) Appl...
45  0.006849  (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_...
46  0.006849  (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_0...
47  0.006849                               (Go-http-client/1.1)
48  0.006849                           (python-requests/2.32.3)
49  0.006849  (Mozilla/5.0 (Windows NT 6.0) AppleWebKit/535....

In [6]:
frequent_itemsets["length"] = frequent_itemsets["itemsets"].apply(lambda x: len(x))
### alternatively:
#frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
#frequent_itemsets = fpmax(df, min_support=0.6, use_colnames=True)

frequent_itemsets

     support                                           itemsets  length
0   0.109589                                      (curl/7.68.0)       1
1   0.068493  (Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...       1
2   0.041096  (Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...       1
3   0.116438                                  (Hello World/1.0)       1
4   0.143836  (Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...       1
5   0.136986  (Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 lik...       1
6   0.006849  (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/5...       1
7   0.013699  (Mozilla/5.0 (compatible; CensysInspect/1.1; +...       1
8   0.006849  (Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...       1
9   0.013699  (Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71...       1
10  0.013699  (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:...       1
11  0.006849  (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:...       1
12  0.013699                                             (xfa1)       1
13  0.006849  (Mozilla/5.0; Keydrop.io/1.0(onlyscans.com/abo...       1
14  0.006849                            (Mozilla/5.0 zgrab/0.x)       1
15  0.013699                                      (Mozilla/5.0)       1
16  0.013699  (Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...       1
17  0.006849  (Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; ...       1
18  0.006849  (Mozilla/5.0 (iPad; CPU OS 7_0 like Mac OS X) ...       1
19  0.006849  (Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:14...       1
20  0.006849  (Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...       1
21  0.006849  (Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...       1
22  0.006849  (Expanse, a Palo Alto Networks company, search...       1
23  0.006849  (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_...       1
24  0.006849  (Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...       1
25  0.020548                                   (l9tcpid/v1.1.0)       1
26  0.020548                                  (l9explore/1.2.2)       1
27  0.006849                (Mozilla/5.0 (PLAYSTATION 3; 1.10))       1
28  0.006849  (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_2...       1
29  0.013699  (Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...       1
30  0.013699  (Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:13...       1
31  0.006849  (Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWeb...       1
32  0.006849  (Mozilla/5.0 (Linux; Android 8.0.0; SM-G930F) ...       1
33  0.006849                           (python-requests/2.32.4)       1
34  0.006849  (Mozilla/5.0 (Windows; U; Windows NT 6.1; en-U...       1
35  0.006849  (Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...       1
36  0.006849               (Opera/9.10 (Windows NT 5.1; U; hu))       1
37  0.006849   (Opera/9.64(Windows NT 5.1; U; en) Presto/2.1.1)       1
38  0.006849  (Mozilla/5.0 (Windows; U; Windows NT 5.1; en-G...       1
39  0.006849  (Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebK...       1
40  0.006849  (Mozilla/5.0 (Windows; U; Windows NT 6.1; en; ...       1
41  0.006849  (Mozilla/5.0 (Windows NT 6.2; Win64; x64) Appl...       1
42  0.006849  (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:...       1
43  0.006849  (Mozilla/5.0 (Linux; Android 9; SAMSUNG SM-G97...       1
44  0.006849  (Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) Appl...       1
45  0.006849  (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_...       1
46  0.006849  (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_0...       1
47  0.006849                               (Go-http-client/1.1)       1
48  0.006849                           (python-requests/2.32.3)       1
49  0.006849  (Mozilla/5.0 (Windows NT 6.0) AppleWebKit/535....       1

In [7]:
large_frequent_itemsets = frequent_itemsets[frequent_itemsets["length"] >= 3]
large_frequent_itemsets

Empty DataFrame
Columns: [support, itemsets, length]
Index: []

In [8]:
import psycopg2

conn = psycopg2.connect(database="web_honeypot_vps", user = "postgres", password = "admin", host = "127.0.0.1", port = "5432")

print("Opened database successfully")

Opened database successfully

In [9]:
# create table
cur = conn.cursor()
cur.execute('''CREATE TABLE assoc_rules_user_agents (
            ID INT PRIMARY KEY     NOT NULL,
            SUPPORT           REAL    NOT NULL,
            USER_AGENT            TEXT     NOT NULL);''')

print("Table created successfully")

conn.commit()

Table created successfully

In [10]:
# insert data

cur = conn.cursor()

insert_query = """
    INSERT INTO assoc_rules_user_agents (ID, SUPPORT, USER_AGENT)
    VALUES (%s, %s, %s)
"""

for idx, row in frequent_itemsets.iterrows():
    cur.execute(
        insert_query,
        (int(idx), float(row["support"]), str(list(row["itemsets"])))
    )

conn.commit()
print("Records created successfully")
conn.close()

Records created successfully

In [10]:
# create table
cur = conn.cursor()
cur.execute('''CREATE TABLE assoc_rules_user_agents_large (
            ID INT PRIMARY KEY     NOT NULL,
            SUPPORT           REAL    NOT NULL,
            USER_AGENT            TEXT     NOT NULL);''')

print("Table created successfully")

conn.commit()

InterfaceError: connection already closed

In [ ]:
# insert data

cur = conn.cursor()

insert_query = """
    INSERT INTO assoc_rules_user_agents_large (ID, SUPPORT, USER_AGENT)
    VALUES (%s, %s, %s)
"""

for idx, row in large_frequent_itemsets.iterrows():
    cur.execute(
        insert_query,
        (int(idx), float(row["support"]), str(list(row["itemsets"])))
    )

conn.commit()
print("Records created successfully")
conn.close()

Records created successfully