In [1]:
import pandas as pd

df = pd.read_json("../../datas/vps/detected.json", lines=True)
# df = pd.read_json("../detected.json", lines=True)

df.head(5)

,method,path,headers,uuid,peer,status,cookies,response_msg,timestamp,post_data
0,GET,/,"{'host': 'localhost', 'user-agent': 'curl/7.68...",64644ea7-b358-4208-9b28-e5aaad5e00de,"{'ip': '172.18.0.1', 'port': 53212}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-14 07:30:36.539037,NaN
1,GET,/,"{'host': '202.10.35.215', 'connection': 'keep-...",64644ea7-b358-4208-9b28-e5aaad5e00de,"{'ip': '180.248.32.210', 'port': 30702}",200,{'sess_uuid': '7ee68b0c-9f55-47e5-b872-078d30b...,"{'version': '0.6.0', 'response': {'message': {...",2025-06-14 07:31:01.702421,NaN
2,GET,/stylesheets/jquery/jquery-ui-1.11.0.css?15286...,"{'host': '202.10.35.215', 'connection': 'keep-...",64644ea7-b358-4208-9b28-e5aaad5e00de,"{'ip': '180.248.32.210', 'port': 30702}",200,{'sess_uuid': 'c3f38f1d-a1be-477a-8692-9369ce7...,"{'version': '0.6.0', 'response': {'message': {...",2025-06-14 07:31:01.860896,NaN
3,GET,/stylesheets/application.css?1528612569,"{'host': '202.10.35.215', 'connection': 'keep-...",64644ea7-b358-4208-9b28-e5aaad5e00de,"{'ip': '180.248.32.210', 'port': 30709}",200,{'sess_uuid': 'c3f38f1d-a1be-477a-8692-9369ce7...,"{'version': '0.6.0', 'response': {'message': {...",2025-06-14 07:31:02.008505,NaN
4,GET,/stylesheets/responsive.css?1528612569,"{'host': '202.10.35.215', 'connection': 'keep-...",64644ea7-b358-4208-9b28-e5aaad5e00de,"{'ip': '180.248.32.210', 'port': 8026}",200,{'sess_uuid': 'c3f38f1d-a1be-477a-8692-9369ce7...,"{'version': '0.6.0', 'response': {'message': {...",2025-06-14 07:31:02.020142,NaN

In [2]:
attacks_matrix = []
tmp = []
sess_uuids_attacks = {
  # "{sess_uuid}": []
}
sess_uuids = []

for _, row in df.iterrows():
  sess_uuid = row.get("cookies", {}).get("sess_uuid") or row.get("response_msg", {}).get("response", {}).get("message", {}).get("sess_uuid")
  detection = row.get("response_msg", {}).get("response", {}).get("message", {}).get("detection", {})
  attack_type = detection.get("name", "")

  if sess_uuid in sess_uuids:
    sess_uuids_attacks[sess_uuid].append(attack_type)
  else:
    sess_uuids_attacks[sess_uuid] = [attack_type]
    sess_uuids.append(sess_uuid)

attacks_matrix = list(sess_uuids_attacks.values())
# for paths in sess_uuids_attacks.values():
#   attacks_matrix.append(paths)

sess_uuids_attacks
# attacks_matrix
# print(len(attacks_matrix), len(sess_uuids_paths.keys()))

{'806c8d58-b04f-4634-b107-34877af9d1d0': ['index'],
 '7ee68b0c-9f55-47e5-b872-078d30b9116b': ['index'],
 'c3f38f1d-a1be-477a-8692-9369ce7d2c44': ['index',
  'index',
  'index',
  'index',
  'index',
  'index',
  'index'],
 'f278a7c1-0785-48d7-bf05-539b1f48cc0c': ['index'],
 '35356d10-0d1c-47ab-b018-36f62dd2a08f': ['lfi'],
 '1e975ea3-2f2c-4183-a4ca-7637ddbe1eec': ['index',
  'index',
  'index',
  'index',
  'index',
  'index',
  'index',
  'index',
  'index'],
 '7c28e45f-7aaa-42fa-b44d-0216a25150ab': ['index',
  'index',
  'index',
  'index',
  'index',
  'index',
  'index',
  'index',
  'index'],
 '47685c7c-17cb-4303-8a1e-5e99a9e1f9bd': ['xss',
  'index',
  'index',
  'index',
  'index',
  'index',
  'index',
  'index'],
 '09e54ba6-8322-4a86-afa8-a01dc89cb59b': ['lfi',
  'index',
  'index',
  'index',
  'index',
  'index',
  'index',
  'index'],
 '98ea628e-45bf-4a62-a0ee-3fab57dbf91d': ['index',
  'index',
  'index',
  'index',
  'index',
  'index',
  'index',
  'index',
  'index'],
 'fd70efc6-4bea-4488-9b48-259dedb17253': ['sqli'],
 '832ea6af-7ac1-4971-b205-2028efaef538': ['index'],
 'a32ff6ba-c480-4519-b91e-539517820571': ['index'],
 '5a39f903-3016-4ecc-990e-e20e8813115d': ['index'],
 'f98db070-b1c2-4f1e-b019-c13361eeef96': ['index'],
 '8de81429-7607-4d4f-b31c-5e03ff10e2bd': ['index'],
 '997a2bbc-7e8a-4088-9fb5-05809cdcaf81': ['index'],
 'f7358105-0eb0-474a-ba3e-6266aca8f90a': ['index', 'index'],
 '623bcb95-5794-42ea-86e6-b1af1a13158c': ['index'],
 'bbed53f4-35ef-4722-b8df-269a46a691f1': ['index',
  'unknown',
  'index',
  'unknown'],
 '76b1da02-e6c1-4826-b881-a504aefb8f0b': ['index'],
 '3d120c94-fd09-4619-adcb-715466a1b85f': ['index',
  'index',
  'index',
  'index',
  'index',
  'index'],
 'c9f54414-6d3d-4ab0-84d9-b17a5bc56abe': ['index'],
 '67ad7734-1a0d-44c4-91fb-f5a95e0cb51f': ['index'],
 '4021c006-9db4-4278-af06-808ead00ba8f': ['index'],
 '28e88c97-5ccb-4526-8113-1d65eb3aa43b': ['index', 'index'],
 'df46768d-6cf6-4b4e-bc82-7cff4ca4a9c1': ['index'],
 'e6dc69dd-97c6-4a9d-a842-8a1802e8e0c5': ['index'],
 '252b722b-5181-4089-a148-0e6c2eedee0d': ['index'],
 '5a619609-691d-485b-ba0c-4d7ce6d9e18a': ['index', 'index'],
 'f629a009-4764-4dcf-9121-953912923945': ['index'],
 'cc4fde00-f118-490f-b158-2eab31ebdd6c': ['index'],
 '1d20892e-df9a-4816-949f-6416fa32a10a': ['index'],
 '10760847-7b34-4af7-b53e-1dc0562d21c0': ['index'],
 '356a10a8-c46b-4c4f-b990-5a87e9626ac2': ['index'],
 '9ac9975c-b405-45ff-8c33-814145f20dfd': ['index'],
 'd0f4dd71-e8c1-4e83-b0ae-0a578031fdb5': ['index'],
 '1face405-0fa0-40f4-acc5-33f957af9033': ['index'],
 '8d7db90d-79e6-4029-98f8-324c3d9a3ebb': ['index'],
 '22f29eb6-221d-4870-8b83-fd04e7d5c30d': ['index'],
 'ac8bf79c-726f-4aa0-8f12-61b3df10efe8': ['index'],
 '7738d8a9-292a-4497-904a-7651efcd8f99': ['index'],
 'a0c8a814-cfc0-4668-bb7d-9c73356c8fbe': ['index', 'index'],
 'c5b8cd87-50cd-4d14-93aa-b3389af9efe1': ['index'],
 '1df72535-5045-4145-a395-90c20d2c7c11': ['index'],
 '0ed39147-fed9-4179-82c4-4ff84f92531f': ['index'],
 '047aa8f9-0d61-433b-8f59-f5f6f8daf6c3': ['index'],
 'c5dd7888-775b-47a9-a28c-f32584abf216': ['index'],
 '375ebac4-4589-42e5-be80-2a9a53f64a79': ['index'],
 '90fb3a1d-d449-409d-a2b4-f32e6ee3ebd5': ['index', 'index'],
 '1500fa23-b233-4ab6-9e42-9506f8d9a8f5': ['index'],
 'a876e6c1-6364-4a9a-84e4-41c948ea098a': ['index'],
 'b4580408-1ae0-4a35-967f-8b76025da5f4': ['index'],
 'fdfea6b2-7629-4525-b94e-994d0e1b4c02': ['index', 'index'],
 'a1f02805-3232-478b-afc7-933f606700fe': ['index'],
 '8e4e6af6-8732-476a-b29f-d0a0d0fd7cf1': ['index'],
 '8d8e54c9-574e-4ae1-8a1f-24cd557d6efc': ['index'],
 'ed57daaa-8e5a-4748-91bf-bf12f95605c3': ['unknown'],
 '4a1d05e4-7d48-4e60-a4b6-d68543ee6f4e': ['index'],
 '1af6395b-05c0-49e9-a63d-31774b8cc443': ['index'],
 'c8c7da1a-0809-4459-b070-f860ed4b6e90': ['index'],
 '5e63f4e3-72a3-4606-a7d7-607202abd111': ['index', 'index'],
 'b44b53e8-b996-44cd-9701-0b1acf642b74': ['index'],
 '886bacbd-0835-41af-97fc-4077f5410d07': ['index'],
 'b72a5770-2033-454c-b116-3a58b0a0fb70': ['index',
  'index',
  'index',
  'index',
  'index',
  'index'],
 '4cc3e677-ae7f-4272-ac1e-e80e4a528a99': ['index'],
 '788a58e6-faf9-4329-9c7e-0d6d3b6bb778': ['index', 'index'],
 'a095275f-688e-4743-9df6-a56cc877f543': ['unknown'],
 'f8d5daeb-62a8-4332-9b88-3da8f0052d77': ['index'],
 '17ebd84f-9971-4643-8a31-7cc8cd1b82b6': ['index'],
 '7aea6c15-f917-460b-ad42-c7226e11fb0f': ['index', 'index'],
 '8fd1aabe-0fc9-4081-837c-6e44298b03ca': ['index', 'index', 'index'],
 '7b7eff7e-0382-4f4f-a60b-f6e9c63fb508': ['index',
  'index',
  'index',
  'index',
  'index',
  'index',
  'index',
  'index',
  'index',
  'index',
  'index',
  'index',
  'index',
  'index',
  'index',
  'index'],
 'be507312-77b8-4192-a2ee-ada36d8d9a47': ['index'],
 'e473dd7b-425b-4d0e-add0-2e0b94b987b3': ['index'],
 '1f50e10a-909e-4aad-87ac-2e4ad69c4b78': ['index'],
 '1c270e8f-15cc-4bed-af51-56c06398b164': ['index'],
 'f8712c2e-b44e-4f46-b720-6bfceef0830b': ['index', 'index'],
 '2561401f-b324-4abc-b305-5f36bf9378d6': ['index'],
 'a051cb03-6c18-45fd-befb-0f540ab3e30f': ['index', 'unknown'],
 'd5ed6912-3978-4939-907a-ba7bc84a62ad': ['index'],
 '55475a8b-364e-42f9-9637-d70f0e803c95': ['index'],
 '31bb5d74-0b1d-4d22-bd1c-3387e4d02925': ['index'],
 'efda917b-8df0-4a67-a23f-226ce2d4142d': ['index'],
 '31db0f15-906f-4e4d-b2d1-0880775f4092': ['index'],
 'f0c9c43d-c183-4759-a6ad-59d6d223a5b9': ['index'],
 '870afd59-9344-4da7-bc46-990968d5bcfa': ['index'],
 '941306f1-ce4e-4bb1-aea2-6da90b1d653c': ['index', 'index'],
 'd3285eb8-e726-4b4f-9d3c-ada2141f7dc5': ['index'],
 'd00ed0ca-1623-4c75-991e-8f98c6fe56ab': ['index'],
 '266fbad5-f5fb-40df-ba3e-f4cf0066d2d0': ['index', 'index'],
 'b21943c4-e1f9-4fb1-80cb-702d08b91f46': ['index', 'index'],
 '6e459258-0fdf-4be6-9d9a-f60e84c9d0af': ['index'],
 'e3b2a072-1bfc-445f-a1e6-c2e44d9305ec': ['index'],
 'cfc4c1ab-57e4-4fec-a759-90028b90b35c': ['cmd_exec', 'cmd_exec'],
 'd16e3a2f-05a7-40be-855e-5b810b524b61': ['index'],
 '1f2c44ee-051a-4dbf-bbef-bad76026db84': ['index'],
 '699bfb4e-35a6-4719-8c6e-30f20c46dd55': ['index'],
 'bab1893c-f936-4d07-bb9d-4ffd1556736b': ['index'],
 'aca366aa-3e72-456d-ac50-11809f7ed76e': ['index'],
 'e5bb3af1-9da0-4965-8cd0-f193b2b423ae': ['index'],
 'b37730f6-6614-468f-8c53-cff0cf8d23e9': ['index']}

In [3]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, fpmax, fpgrowth

te = TransactionEncoder()
te_ary = te.fit(attacks_matrix).transform(attacks_matrix)
df = pd.DataFrame(te_ary, columns=te.columns_)

df.head(10)

   cmd_exec  index    lfi   sqli  unknown    xss
0     False   True  False  False    False  False
1     False   True  False  False    False  False
2     False   True  False  False    False  False
3     False   True  False  False    False  False
4     False  False   True  False    False  False
5     False   True  False  False    False  False
6     False   True  False  False    False  False
7     False   True  False  False    False   True
8     False   True   True  False    False  False
9     False   True  False  False    False  False

In [4]:
# frequent_itemsets = fpgrowth(df, min_support=0.3, use_colnames=True)
frequent_itemsets = fpgrowth(df, min_support=0.00001, use_colnames=True)
frequent_itemsets["length"] = frequent_itemsets["itemsets"].apply(lambda x: len(x))
### alternatively:
#frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
#frequent_itemsets = fpmax(df, min_support=0.6, use_colnames=True)

frequent_itemsets

    support          itemsets  length
0  0.950980           (index)       1
1  0.019608             (lfi)       1
2  0.009804             (xss)       1
3  0.009804            (sqli)       1
4  0.039216         (unknown)       1
5  0.009804        (cmd_exec)       1
6  0.009804      (index, lfi)       2
7  0.009804      (index, xss)       2
8  0.019608  (index, unknown)       2

In [5]:
large_frequent_itemsets = frequent_itemsets[frequent_itemsets["length"] >= 3]
large_frequent_itemsets

Empty DataFrame
Columns: [support, itemsets, length]
Index: []

In [6]:
import psycopg2

conn = psycopg2.connect(database="web_honeypot_vps", user = "postgres", password = "admin", host = "127.0.0.1", port = "5432")

print("Opened database successfully")

Opened database successfully

In [7]:
# create table
cur = conn.cursor()
cur.execute('''CREATE TABLE assoc_rules_attack_types (
            ID INT PRIMARY KEY     NOT NULL,
            SUPPORT           REAL    NOT NULL,
            ATTACK_TYPE            VARCHAR(255)     NOT NULL);''')

print("Table created successfully")

conn.commit()

Table created successfully

In [8]:
# insert data

cur = conn.cursor()

insert_query = """
    INSERT INTO assoc_rules_attack_types (ID, SUPPORT, ATTACK_TYPE)
    VALUES (%s, %s, %s)
"""

for idx, row in frequent_itemsets.iterrows():
    cur.execute(
        insert_query,
        (int(idx), float(row["support"]), str(list(row["itemsets"])))
    )

conn.commit()
print("Records created successfully")
conn.close()

Records created successfully

In [9]:
# create large data table
cur = conn.cursor()
cur.execute('''CREATE TABLE assoc_rules_attack_types_large (
            ID INT PRIMARY KEY     NOT NULL,
            SUPPORT           REAL    NOT NULL,
            ATTACK_TYPE            VARCHAR(255)     NOT NULL);''')

print("Table created successfully")

conn.commit()

InterfaceError: connection already closed

In [ ]:
# insert large data

cur = conn.cursor()

insert_query = """
    INSERT INTO assoc_rules_attack_types_large (ID, SUPPORT, ATTACK_TYPE)
    VALUES (%s, %s, %s)
"""

for idx, row in large_frequent_itemsets.iterrows():
    cur.execute(
        insert_query,
        (int(idx), float(row["support"]), str(list(row["itemsets"])))
    )

conn.commit()
print("Records created successfully")
conn.close()

Records created successfully