In [1]:
import pandas as pd

df = pd.read_json("../../datas/vps/detected.json", lines=True)

df.head(5)

,method,path,headers,uuid,peer,status,cookies,response_msg,timestamp,post_data
0,GET,/,"{'host': 'localhost', 'user-agent': 'curl/7.68...",64644ea7-b358-4208-9b28-e5aaad5e00de,"{'ip': '172.18.0.1', 'port': 53212}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-14 07:30:36.539037,NaN
1,GET,/,"{'host': '202.10.35.215', 'connection': 'keep-...",64644ea7-b358-4208-9b28-e5aaad5e00de,"{'ip': '180.248.32.210', 'port': 30702}",200,{'sess_uuid': '7ee68b0c-9f55-47e5-b872-078d30b...,"{'version': '0.6.0', 'response': {'message': {...",2025-06-14 07:31:01.702421,NaN
2,GET,/stylesheets/jquery/jquery-ui-1.11.0.css?15286...,"{'host': '202.10.35.215', 'connection': 'keep-...",64644ea7-b358-4208-9b28-e5aaad5e00de,"{'ip': '180.248.32.210', 'port': 30702}",200,{'sess_uuid': 'c3f38f1d-a1be-477a-8692-9369ce7...,"{'version': '0.6.0', 'response': {'message': {...",2025-06-14 07:31:01.860896,NaN
3,GET,/stylesheets/application.css?1528612569,"{'host': '202.10.35.215', 'connection': 'keep-...",64644ea7-b358-4208-9b28-e5aaad5e00de,"{'ip': '180.248.32.210', 'port': 30709}",200,{'sess_uuid': 'c3f38f1d-a1be-477a-8692-9369ce7...,"{'version': '0.6.0', 'response': {'message': {...",2025-06-14 07:31:02.008505,NaN
4,GET,/stylesheets/responsive.css?1528612569,"{'host': '202.10.35.215', 'connection': 'keep-...",64644ea7-b358-4208-9b28-e5aaad5e00de,"{'ip': '180.248.32.210', 'port': 8026}",200,{'sess_uuid': 'c3f38f1d-a1be-477a-8692-9369ce7...,"{'version': '0.6.0', 'response': {'message': {...",2025-06-14 07:31:02.020142,NaN

In [2]:
ports_matrix = []
tmp = []
sess_uuids_ports = {
  # "{sess_uuid}": []
}
sess_uuids = []

for _, row in df.iterrows():
  sess_uuid = row.get("cookies", {}).get("sess_uuid") or row.get("response_msg", {}).get("response", {}).get("message", {}).get("sess_uuid")
  port = row["peer"]["port"]

  if sess_uuid in sess_uuids:
    sess_uuids_ports[sess_uuid].append(port)
  else:
    sess_uuids_ports[sess_uuid] = [port]
    sess_uuids.append(sess_uuid)

ports_matrix = list(sess_uuids_ports.values())
# for paths in sess_uuids_ports.values():
#   ports_matrix.append(paths)

sess_uuids_ports
# ports_matrix
# print(len(ports_matrix), len(sess_uuids_ports.keys()))

{'806c8d58-b04f-4634-b107-34877af9d1d0': [53212],
 '7ee68b0c-9f55-47e5-b872-078d30b9116b': [30702],
 'c3f38f1d-a1be-477a-8692-9369ce7d2c44': [30702,
  30709,
  8026,
  8024,
  30707,
  30702,
  8024],
 'f278a7c1-0785-48d7-bf05-539b1f48cc0c': [8024],
 '35356d10-0d1c-47ab-b018-36f62dd2a08f': [8024],
 '1e975ea3-2f2c-4183-a4ca-7637ddbe1eec': [49608,
  50269,
  31205,
  50270,
  31206,
  50266,
  50271,
  11150,
  48899],
 '7c28e45f-7aaa-42fa-b44d-0216a25150ab': [57778,
  23989,
  34673,
  34671,
  34672,
  34675,
  34674,
  29378,
  31583],
 '47685c7c-17cb-4303-8a1e-5e99a9e1f9bd': [21654,
  12487,
  12486,
  12489,
  12488,
  12490,
  12491,
  65352],
 '09e54ba6-8322-4a86-afa8-a01dc89cb59b': [24854,
  44088,
  31409,
  44090,
  44091,
  31411,
  44092,
  10023],
 '98ea628e-45bf-4a62-a0ee-3fab57dbf91d': [25714,
  50773,
  31453,
  31451,
  12766,
  12765,
  12770,
  12768,
  14827],
 'fd70efc6-4bea-4488-9b48-259dedb17253': [51321],
 '832ea6af-7ac1-4971-b205-2028efaef538': [53368],
 'a32ff6ba-c480-4519-b91e-539517820571': [53570],
 '5a39f903-3016-4ecc-990e-e20e8813115d': [49928],
 'f98db070-b1c2-4f1e-b019-c13361eeef96': [33794],
 '8de81429-7607-4d4f-b31c-5e03ff10e2bd': [60656],
 '997a2bbc-7e8a-4088-9fb5-05809cdcaf81': [35668],
 'f7358105-0eb0-474a-ba3e-6266aca8f90a': [57156, 33548],
 '623bcb95-5794-42ea-86e6-b1af1a13158c': [38710],
 'bbed53f4-35ef-4722-b8df-269a46a691f1': [58328, 65384, 55878, 63286],
 '76b1da02-e6c1-4826-b881-a504aefb8f0b': [57512],
 '3d120c94-fd09-4619-adcb-715466a1b85f': [57922,
  58164,
  58190,
  36062,
  52940,
  52954],
 'c9f54414-6d3d-4ab0-84d9-b17a5bc56abe': [50318],
 '67ad7734-1a0d-44c4-91fb-f5a95e0cb51f': [32920],
 '4021c006-9db4-4278-af06-808ead00ba8f': [37038],
 '28e88c97-5ccb-4526-8113-1d65eb3aa43b': [36950, 36966],
 'df46768d-6cf6-4b4e-bc82-7cff4ca4a9c1': [40656],
 'e6dc69dd-97c6-4a9d-a842-8a1802e8e0c5': [60722],
 '252b722b-5181-4089-a148-0e6c2eedee0d': [39582],
 '5a619609-691d-485b-ba0c-4d7ce6d9e18a': [47090, 41780],
 'f629a009-4764-4dcf-9121-953912923945': [51728],
 'cc4fde00-f118-490f-b158-2eab31ebdd6c': [50606],
 '1d20892e-df9a-4816-949f-6416fa32a10a': [40152],
 '10760847-7b34-4af7-b53e-1dc0562d21c0': [46880],
 '356a10a8-c46b-4c4f-b990-5a87e9626ac2': [57828],
 '9ac9975c-b405-45ff-8c33-814145f20dfd': [44828],
 'd0f4dd71-e8c1-4e83-b0ae-0a578031fdb5': [33964],
 '1face405-0fa0-40f4-acc5-33f957af9033': [58842],
 '8d7db90d-79e6-4029-98f8-324c3d9a3ebb': [61317],
 '22f29eb6-221d-4870-8b83-fd04e7d5c30d': [28971],
 'ac8bf79c-726f-4aa0-8f12-61b3df10efe8': [57591],
 '7738d8a9-292a-4497-904a-7651efcd8f99': [53050],
 'a0c8a814-cfc0-4668-bb7d-9c73356c8fbe': [44412, 48218],
 'c5b8cd87-50cd-4d14-93aa-b3389af9efe1': [46584],
 '1df72535-5045-4145-a395-90c20d2c7c11': [41956],
 '0ed39147-fed9-4179-82c4-4ff84f92531f': [61002],
 '047aa8f9-0d61-433b-8f59-f5f6f8daf6c3': [43782],
 'c5dd7888-775b-47a9-a28c-f32584abf216': [55524],
 '375ebac4-4589-42e5-be80-2a9a53f64a79': [39168],
 '90fb3a1d-d449-409d-a2b4-f32e6ee3ebd5': [33714, 33730],
 '1500fa23-b233-4ab6-9e42-9506f8d9a8f5': [45398],
 'a876e6c1-6364-4a9a-84e4-41c948ea098a': [33972],
 'b4580408-1ae0-4a35-967f-8b76025da5f4': [36394],
 'fdfea6b2-7629-4525-b94e-994d0e1b4c02': [46458, 56278],
 'a1f02805-3232-478b-afc7-933f606700fe': [54688],
 '8e4e6af6-8732-476a-b29f-d0a0d0fd7cf1': [47210],
 '8d8e54c9-574e-4ae1-8a1f-24cd557d6efc': [35370],
 'ed57daaa-8e5a-4748-91bf-bf12f95605c3': [47288],
 '4a1d05e4-7d48-4e60-a4b6-d68543ee6f4e': [42758],
 '1af6395b-05c0-49e9-a63d-31774b8cc443': [33706],
 'c8c7da1a-0809-4459-b070-f860ed4b6e90': [35626],
 '5e63f4e3-72a3-4606-a7d7-607202abd111': [35772, 41406],
 'b44b53e8-b996-44cd-9701-0b1acf642b74': [40210],
 '886bacbd-0835-41af-97fc-4077f5410d07': [58372],
 'b72a5770-2033-454c-b116-3a58b0a0fb70': [36188,
  47766,
  47772,
  47780,
  47784,
  47800],
 '4cc3e677-ae7f-4272-ac1e-e80e4a528a99': [36500],
 '788a58e6-faf9-4329-9c7e-0d6d3b6bb778': [46806, 48146],
 'a095275f-688e-4743-9df6-a56cc877f543': [40878],
 'f8d5daeb-62a8-4332-9b88-3da8f0052d77': [39246],
 '17ebd84f-9971-4643-8a31-7cc8cd1b82b6': [33474],
 '7aea6c15-f917-460b-ad42-c7226e11fb0f': [58380, 58380],
 '8fd1aabe-0fc9-4081-837c-6e44298b03ca': [58380, 58380, 58380],
 '7b7eff7e-0382-4f4f-a60b-f6e9c63fb508': [58380,
  58380,
  58380,
  58380,
  58380,
  58380,
  58380,
  58380,
  58380,
  58380,
  58380,
  58380,
  58380,
  58380,
  58380,
  58380],
 'be507312-77b8-4192-a2ee-ada36d8d9a47': [60000],
 'e473dd7b-425b-4d0e-add0-2e0b94b987b3': [52928],
 '1f50e10a-909e-4aad-87ac-2e4ad69c4b78': [33828],
 '1c270e8f-15cc-4bed-af51-56c06398b164': [34796],
 'f8712c2e-b44e-4f46-b720-6bfceef0830b': [54570, 60758],
 '2561401f-b324-4abc-b305-5f36bf9378d6': [48436],
 'a051cb03-6c18-45fd-befb-0f540ab3e30f': [36644, 36670],
 'd5ed6912-3978-4939-907a-ba7bc84a62ad': [33860],
 '55475a8b-364e-42f9-9637-d70f0e803c95': [43850],
 '31bb5d74-0b1d-4d22-bd1c-3387e4d02925': [39426],
 'efda917b-8df0-4a67-a23f-226ce2d4142d': [54980],
 '31db0f15-906f-4e4d-b2d1-0880775f4092': [60146],
 'f0c9c43d-c183-4759-a6ad-59d6d223a5b9': [35534],
 '870afd59-9344-4da7-bc46-990968d5bcfa': [33904],
 '941306f1-ce4e-4bb1-aea2-6da90b1d653c': [47798, 58570],
 'd3285eb8-e726-4b4f-9d3c-ada2141f7dc5': [39780],
 'd00ed0ca-1623-4c75-991e-8f98c6fe56ab': [50556],
 '266fbad5-f5fb-40df-ba3e-f4cf0066d2d0': [37016, 50514],
 'b21943c4-e1f9-4fb1-80cb-702d08b91f46': [37020, 50522],
 '6e459258-0fdf-4be6-9d9a-f60e84c9d0af': [52006],
 'e3b2a072-1bfc-445f-a1e6-c2e44d9305ec': [59474],
 'cfc4c1ab-57e4-4fec-a759-90028b90b35c': [34152, 34168],
 'd16e3a2f-05a7-40be-855e-5b810b524b61': [34486],
 '1f2c44ee-051a-4dbf-bbef-bad76026db84': [60000],
 '699bfb4e-35a6-4719-8c6e-30f20c46dd55': [49044],
 'bab1893c-f936-4d07-bb9d-4ffd1556736b': [25678],
 'aca366aa-3e72-456d-ac50-11809f7ed76e': [42058],
 'e5bb3af1-9da0-4965-8cd0-f193b2b423ae': [50083],
 'b37730f6-6614-468f-8c53-cff0cf8d23e9': [48331],
 'b4b2b17d-d292-47f8-9257-01830d313ae1': [34562],
 'd20be2c1-a120-4de4-94f1-474235f9c348': [46275],
 '0c4cff42-3743-4b68-b3b7-36f3b2fb188d': [37370,
  37416,
  34836,
  39362,
  39368,
  34710],
 '8431c9e0-a5e4-46a5-9878-90707213d930': [43910, 35296],
 'fc3bf6c6-8482-426c-946a-4b1ba170c199': [48800],
 '2641268e-75f3-475d-af52-c900d31271ad': [34544],
 'de6dd592-14b5-4bb6-92bb-18ff8abc824c': [37370],
 '55769149-07b6-4749-bbaa-d0df08fc2e30': [47456],
 '9b5a36dc-e1c3-4475-97cb-239384c081ca': [61002],
 '11b5a22e-0363-41f7-8d3f-365b8606a054': [46248],
 '0d785779-8cbd-4f1d-9250-e3e6d654e263': [42348],
 '10fa9ee6-873c-4780-9a19-bfed11044f16': [50558],
 '58152224-fefc-48dc-afa3-d793e0a8751e': [34528],
 '1d64153a-93af-4adb-b5fa-3b2d54180c74': [47266],
 '0765b697-19b8-458f-8c39-35c2a5dbd4e8': [53940],
 'e5c02419-ae0a-4858-8522-1e8c9be0cb77': [59630],
 '25634633-1fd4-4b42-b424-2e0d00a319b3': [38398],
 'f95bef52-11a0-4551-9dbc-e9e7f2d32d01': [50970],
 '0f8c1aba-a173-4a9e-b27f-a84e0783c1eb': [58088],
 '62985346-cccc-45b2-8fec-37222c5d98af': [36550],
 '9725d4c3-3552-4607-9f9c-96a4e0026d25': [37432],
 'c83a475d-4338-442b-8001-0e0d38b31956': [42970],
 '7c00303f-47ba-4539-beb0-8d9c990f7357': [42540],
 'b5d26698-b551-4560-86c3-4d3ee177babd': [47158],
 '4d58d4ac-5833-4b1c-acf1-6ba0d796736f': [37462],
 '23b5c3dd-6049-42d3-87aa-a1b3df3416c9': [43602],
 '9dea8911-285c-4993-b1d3-50257bb26d45': [37556],
 'ec7e27a3-b079-4354-8084-e073586b77ff': [55454],
 '1b25a153-fc12-4f38-a55e-d50f161d9bf4': [36374],
 '516edec4-6b1e-4ec9-bdd6-c9951c0ce634': [36378],
 'ac2d1343-f801-4411-bb53-46d18fc85e38': [60406],
 'c7a9e64d-0d55-4e8e-abd0-2c287a3f3d83': [52310],
 'cfe5a2ef-b02a-4d97-861f-08ba12db6f96': [42046],
 '4cce0e2e-6886-4bc8-a4ef-fc8a52d9f46a': [38056],
 'e7193848-0ace-4390-a8d0-bbf024b7272f': [53958],
 '997a9a09-0872-4153-bb1e-72cdf4d93dd1': [35146],
 'd31a21a3-922d-4449-ab6f-2bdcad19dbf0': [54908, 39424],
 '133086da-e8e9-435f-ade8-6d6bf1bd067b': [59404],
 '7fbce34f-47ac-4899-9590-fabd5936e28b': [59414],
 '90308f2b-b69c-408c-8a0b-0190a52fad1b': [34506],
 '2aafb35e-6e86-4cd9-aa41-a84b73cdd85e': [40270],
 '727dae92-80c7-4381-837e-1efd67cbcc72': [51931],
 'c4c98f87-7499-4f78-8bc7-9eb2567e5438': [33872],
 '5845f689-3930-4e2d-beab-c7a25d7b1690': [33250, 33256, 33262, 33296],
 '2a00aa78-9e78-4b8e-947e-fab6883593c5': [33286, 33270, 33272],
 '3111288c-8e46-4664-8ab6-869604ec77f0': [35190],
 '2957f15c-a15a-43dc-a3c6-e617a42708c4': [58368],
 'bb916666-895d-4787-a709-e050a0facdcb': [39206],
 '2f176122-665e-41bd-af6c-d432e1a5acba': [46830],
 'bf99b83d-395c-4a85-a454-2b14b34a4c7d': [39204],
 'c85c4599-0779-4b5e-845c-139b1529c312': [41470],
 '3105e78d-7170-41f7-a201-f0b635c56e55': [60970],
 '754519e3-1e83-4dbf-b7d4-4775fb960226': [47832]}

In [3]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, fpmax, fpgrowth

te = TransactionEncoder()
te_ary = te.fit(ports_matrix).transform(ports_matrix)
df = pd.DataFrame(te_ary, columns=te.columns_)

df

,8024,8026,10023,11150,12486,12487,12488,12489,12490,12491,...,60406,60656,60722,60758,60970,61002,61317,63286,65352,65384
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,True,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
151,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
152,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
153,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
154,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [5]:
# frequent_itemsets = fpgrowth(df, min_support=0.3, use_colnames=True)
frequent_itemsets = fpgrowth(df, min_support=0.005, use_colnames=True)
### alternatively:
#frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
#frequent_itemsets = fpmax(df, min_support=0.6, use_colnames=True)

frequent_itemsets

       support                      itemsets
0     0.006452                       (53212)
1     0.012903                       (30702)
2     0.019355                        (8024)
3     0.006452                       (30709)
4     0.006452                       (30707)
...        ...                           ...
2462  0.006452  (33256, 33296, 33250, 33262)
2463  0.006452                (33272, 33286)
2464  0.006452                (33272, 33270)
2465  0.006452                (33270, 33286)
2466  0.006452         (33272, 33270, 33286)

[2467 rows x 2 columns]

In [6]:
frequent_itemsets["length"] = frequent_itemsets["itemsets"].apply(lambda x: len(x))
### alternatively:
#frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
#frequent_itemsets = fpmax(df, min_support=0.6, use_colnames=True)

frequent_itemsets

       support                      itemsets  length
0     0.006452                       (53212)       1
1     0.012903                       (30702)       1
2     0.019355                        (8024)       1
3     0.006452                       (30709)       1
4     0.006452                       (30707)       1
...        ...                           ...     ...
2462  0.006452  (33256, 33296, 33250, 33262)       4
2463  0.006452                (33272, 33286)       2
2464  0.006452                (33272, 33270)       2
2465  0.006452                (33270, 33286)       2
2466  0.006452         (33272, 33270, 33286)       3

[2467 rows x 3 columns]

In [7]:
large_frequent_itemsets = frequent_itemsets[frequent_itemsets["length"] >= 3]
large_frequent_itemsets

       support                      itemsets  length
231   0.006452          (8024, 30709, 30702)       3
235   0.006452         (30707, 30709, 30702)       3
236   0.006452          (8024, 30707, 30709)       3
237   0.006452          (8024, 30707, 30702)       3
238   0.006452   (8024, 30707, 30709, 30702)       4
...        ...                           ...     ...
2459  0.006452         (33256, 33250, 33262)       3
2460  0.006452         (33256, 33296, 33250)       3
2461  0.006452         (33296, 33250, 33262)       3
2462  0.006452  (33256, 33296, 33250, 33262)       4
2466  0.006452         (33272, 33270, 33286)       3

[1989 rows x 3 columns]

In [8]:
import psycopg2

conn = psycopg2.connect(database="web_honeypot_vps", user = "postgres", password = "admin", host = "127.0.0.1", port = "5432")

print("Opened database successfully")

Opened database successfully

In [9]:
# create table
cur = conn.cursor()
cur.execute('''CREATE TABLE assoc_rules_ports (
            ID INT PRIMARY KEY     NOT NULL,
            SUPPORT           REAL    NOT NULL,
            PORT            VARCHAR(255)     NOT NULL);''')

print("Table created successfully")

conn.commit()

Table created successfully

In [10]:
# insert data

cur = conn.cursor()

insert_query = """
    INSERT INTO assoc_rules_ports (ID, SUPPORT, PORT)
    VALUES (%s, %s, %s)
"""

for idx, row in frequent_itemsets.iterrows():
    cur.execute(
        insert_query,
        (int(idx), float(row["support"]), str(list(row["itemsets"])))
    )

conn.commit()
print("Records created successfully")

Records created successfully

In [11]:
# create table
cur = conn.cursor()
cur.execute('''CREATE TABLE assoc_rules_ports_large (
            ID INT PRIMARY KEY     NOT NULL,
            SUPPORT           REAL    NOT NULL,
            PORT            VARCHAR(255)     NOT NULL);''')

print("Table created successfully")

conn.commit()

Table created successfully

In [12]:
# insert data

cur = conn.cursor()

insert_query = """
    INSERT INTO assoc_rules_ports_large (ID, SUPPORT, PORT)
    VALUES (%s, %s, %s)
"""

for idx, row in large_frequent_itemsets.iterrows():
    cur.execute(
        insert_query,
        (int(idx), float(row["support"]), str(list(row["itemsets"])))
    )

conn.commit()
print("Records created successfully")
conn.close()

Records created successfully