In [2]:
import pandas as pd

df = pd.read_json("../tanner_report.json", lines=True)

df.head(5)

,method,path,headers,uuid,peer,status,cookies,response_msg,timestamp,post_data
0,GET,/,"{'host': 'localhost', 'user-agent': 'curl/7.81...",50d7b1f4-6ef6-4338-b372-dbd50f852dd9,"{'ip': '172.18.0.1', 'port': 59950}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-08 10:53:33.297062,NaN
1,GET,/,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",50d7b1f4-6ef6-4338-b372-dbd50f852dd9,"{'ip': '172.18.0.1', 'port': 38278}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-08 10:53:45.782025,NaN
2,GET,/,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",50d7b1f4-6ef6-4338-b372-dbd50f852dd9,"{'ip': '172.18.0.1', 'port': 38278}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-08 10:53:45.872072,NaN
3,GET,/robots.txt,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",50d7b1f4-6ef6-4338-b372-dbd50f852dd9,"{'ip': '172.18.0.1', 'port': 38286}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-08 10:53:45.891330,NaN
4,GET,/sitemap.xml,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",50d7b1f4-6ef6-4338-b372-dbd50f852dd9,"{'ip': '172.18.0.1', 'port': 38288}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-08 10:53:45.893769,NaN

In [4]:
paths = df["path"]

# get the paths with params
# filtered_paths = filtered_df["path"]

# get the paths without params
paths = paths.apply(lambda x: x.split('?', 1)[0])

paths_matrix = []
tmp = []

for i, x in enumerate(paths):
  if i % 10 == 0 and i != 0:
    paths_matrix.append(tmp)
    tmp = []
  tmp.append(x)

# Add the last group if not empty
if tmp:
  paths_matrix.append(tmp)

paths_matrix

[['/',
  '/',
  '/',
  '/robots.txt',
  '/sitemap.xml',
  '/',
  '/2018/08/07/hello-world/',
  '/2018/08/',
  '/category/uncategorized/',
  '/wp-login.php'],
 ['/comments/feed/',
  '/wp-content/themes/twentyseventeen/A.style.css,qver=4.9.8.pagespeed.cf.COU0KFbmw7.css',
  '/feed/',
  '/wp-json/',
  '/wp-includes/wlwmanifest.xml',
  '/wp-includes/js/jquery/jquery.js,qver=1.12.4.pagespeed.jm.pPCPAKkkss.js',
  '/wp-content,_themes,_twentyseventeen,_assets,_js,_skip-link-focus-fix.js,qver==1.0+wp-content,_themes,_twentyseventeen,_assets,_js,_global.js,qver==1.0+wp-content,_themes,_twentyseventeen,_assets,_js,_jquery.scrollTo.js,qver==2.1.2+wp-includes,_js,_wp-embed.min.js,qver==4.9.8.pagespeed.jc.J9cS7BYRPe.js',
  '/wp-includes/js/jquery/jquery-migrate.min.js,qver=1.4.1.pagespeed.jm.C2obERNcWh.js',
  '/wp-content/themes/twentyseventeen/assets/images/header.jpg',
  '/wp-includes/js/wp-embed.min.js'],
 ['/wp-content/themes/twentyseventeen/style.css',
  '/xmlrpc.php',
  '/wp-includes/js/jquery/jquery.js',
  '/wp-includes/js/jquery/jquery-migrate.min.js',
  '/wp-content/themes/twentyseventeen/assets/js/skip-link-focus-fix.js',
  '/wp-content/themes/twentyseventeen/assets/js/global.js',
  '/',
  '/wp-login.php',
  '/wp-content/themes/twentyseventeen/assets/js/jquery.scrollTo.js',
  '/wp-admin/load-styles.php'],
 ['/wp-content/themes/twentyseventeen/assets/images/header.jpg.pagespeed.ce.gDBDjAybRU.jpg',
  '/wp-login.php',
  '/wp-login.php',
  '/1691240783893101929.php',
  '/2018/6435622836357206148',
  '/2018/08/7863259049507197216',
  '/2018/08/07/1778863373757822730',
  '/2018/08/07/hello-world/8573353525861334525',
  '/category/1373804646564805819',
  '/category/uncategorized/8996337954417620119'],
 ['/comments/2039428130940389657',
  '/comments/feed/2412742687923633436',
  '/feed/6988381700591695546',
  '/wp-admin/1132579955681800067.php',
  '/wp-content/1351353582473423248',
  '/wp-content/themes/7421135938958987114',
  '/wp-content/themes/twentyseventeen/2999578119709514223',
  '/wp-content/themes/twentyseventeen/assets/2567686778932935359',
  '/wp-content/themes/twentyseventeen/assets/images/7569295256949766536',
  '/wp-content/themes/twentyseventeen/assets/js/8769573861353455811'],
 ['/wp-includes/9178421962600353051',
  '/wp-includes/js/3598584548710725507',
  '/wp-includes/js/jquery/5191551170740085508',
  '/wp-json/8831089284210822944',
  '/2018',
  '/2018/08',
  '/wp-login.php',
  '/wp-login.php',
  '/',
  '/2018/08/07'],
 ['/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/2018/08/07/hello-world',
  '/wp-login.php',
  '/',
  '/wp-login.php',
  '/category',
  '/wp-login.php',
  '/'],
 ['/category/uncategorized',
  '/wp-login.php',
  '/comments',
  '/wp-login.php',
  '/',
  '/comments/feed',
  '/wp-login.php',
  '/feed',
  '/wp-login.php',
  '/wp-admin'],
 ['/wp-login.php',
  '/wp-content',
  '/wp-admin/load-styles.php',
  '/wp-content/themes',
  '/wp-login.php',
  '/wp-admin/load-styles.php',
  '/wp-content/themes/twentyseventeen',
  '/wp-login.php',
  '/wp-content/themes/twentyseventeen/assets',
  '/wp-admin/load-styles.php'],
 ['/wp-login.php',
  '/wp-content/themes/twentyseventeen/assets/images',
  '/wp-admin/load-styles.php',
  '/wp-login.php',
  '/wp-content/themes/twentyseventeen/assets/js',
  '/wp-login.php',
  '/wp-content/themes/twentyseventeen/assets/js/global.js',
  '/wp-includes',
  '/wp-content/themes/twentyseventeen/assets/js/jquery.scrollTo.js',
  '/wp-content/themes/twentyseventeen/assets/js/skip-link-focus-fix.js'],
 ['/wp-login.php',
  '/wp-content/themes/twentyseventeen/style.css',
  '/wp-includes/js',
  '/wp-content/themes/twentyseventeen/assets/js/global.js',
  '/wp-content/themes/twentyseventeen/assets/js/jquery.scrollTo.js',
  '/wp-content/themes/twentyseventeen/assets/js/skip-link-focus-fix.js',
  '/wp-login.php',
  '/wp-content/themes/twentyseventeen/style.css',
  '/wp-includes/js/jquery',
  '/wp-content/themes/twentyseventeen/assets/js/global.js'],
 ['/wp-content/themes/twentyseventeen/assets/js/jquery.scrollTo.js',
  '/wp-json',
  '/wp-content/themes/twentyseventeen/assets/js/skip-link-focus-fix.js',
  '/wp-login.php',
  '/wp-includes/js/jquery/jquery-migrate.min.js',
  '/wp-content/themes/twentyseventeen/style.css',
  '/wp-includes/js/wp-embed.min.js',
  '/wp-includes/js/jquery/jquery.js',
  '/wp-content/themes/twentyseventeen/assets/js/global.js',
  '/wp-content/themes/twentyseventeen/assets/js/jquery.scrollTo.js'],
 ['/wp-login.php',
  '/xmlrpc.php',
  '/wp-login.php',
  '/wp-content/themes/twentyseventeen/assets/js/skip-link-focus-fix.js',
  '/wp-content/themes/twentyseventeen/style.css',
  '/wp-includes/js/jquery/jquery-migrate.min.js',
  '/wp-includes/js/wp-embed.min.js',
  '/wp-includes/js/jquery/jquery.js',
  '/wp-login.php',
  '/xmlrpc.php'],
 ['/wp-login.php',
  '/wp-includes/js/jquery/jquery-migrate.min.js',
  '/wp-includes/js/wp-embed.min.js',
  '/wp-includes/js/jquery/jquery.js',
  '/wp-login.php',
  '/xmlrpc.php',
  '/wp-includes/js/jquery/jquery-migrate.min.js',
  '/wp-includes/js/wp-embed.min.js',
  '/wp-includes/js/jquery/jquery.js',
  '/wp-login.php'],
 ['/xmlrpc.php',
  '/wp-content/themes/twentyseventeen/assets/js/skip-link-focus-fix.js',
  '/wp-login.php',
  '/wp-content/themes/twentyseventeen/assets/js/jquery.scrollTo.js',
  '/wp-includes/js/wp-embed.min.js',
  '/wp-admin/load-styles.php',
  '/',
  '/wp-login.php',
  '/xmlrpc.php',
  '/wp-content/themes/twentyseventeen/style.css'],
 ['/wp-includes/js/jquery/jquery-migrate.min.js',
  '/wp-content/themes/twentyseventeen/assets/js/global.js',
  '/wp-content/themes/twentyseventeen/style.css',
  '/wp-login.php',
  '/wp-content/themes/twentyseventeen/assets/js/jquery.scrollTo.js',
  '/xmlrpc.php',
  '/wp-includes/js/jquery/jquery.js',
  '/wp-content/themes/twentyseventeen/assets/js/global.js',
  '/wp-includes/js/wp-embed.min.js',
  '/wp-content/themes/twentyseventeen/assets/js/skip-link-focus-fix.js'],
 ['/wp-includes/js/jquery/jquery-migrate.min.js',
  '/wp-login.php',
  '/wp-includes/js/jquery/jquery.js',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-admin/load-styles.php',
  '/wp-admin/load-styles.php'],
 ['/wp-admin/load-styles.php',
  '/wp-admin/load-styles.php',
  '/wp-admin/load-styles.php',
  '/wp-login.php',
  '/',
  '/wp-login.php',
  '/wp-login.php',
  '/',
  '/wp-login.php',
  '/wp-login.php'],
 ['/',
  '/',
  '/wp-login.php',
  '/wp-login.php',
  '/',
  '/wp-login.php',
  '/wp-login.php',
  '/',
  '/wp-login.php',
  '/wp-login.php'],
 ['/',
  '/wp-login.php',
  '/wp-login.php',
  '/',
  '/',
  '/',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php'],
 ['/wp-login.php',
  '/wp-login.php',
  '/wp-admin/load-styles.php',
  '/wp-admin/load-styles.php',
  '/wp-admin/load-styles.php',
  '/wp-admin/load-styles.php',
  '/wp-admin/load-styles.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php'],
 ['/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-admin/load-styles.php',
  '/wp-admin/load-styles.php',
  '/wp-admin/load-styles.php',
  '/wp-admin/load-styles.php',
  '/wp-admin/load-styles.php',
  '/wp-login.php',
  '/wp-login.php'],
 ['/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-admin/load-styles.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php'],
 ['/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/2018',
  '/wp-login.php',
  '/2018/08',
  '/wp-login.php',
  '/2018/08/07'],
 ['/wp-login.php',
  '/2018/08/07/hello-world',
  '/wp-login.php',
  '/category',
  '/wp-login.php',
  '/category/uncategorized',
  '/wp-login.php',
  '/comments',
  '/wp-login.php',
  '/comments/feed'],
 ['/wp-login.php',
  '/feed',
  '/wp-login.php',
  '/wp-admin',
  '/wp-login.php',
  '/wp-content',
  '/wp-content/themes',
  '/wp-content/themes/twentyseventeen',
  '/wp-content/themes/twentyseventeen/assets',
  '/wp-content/themes/twentyseventeen/assets/images'],
 ['/wp-content/themes/twentyseventeen/assets/js',
  '/wp-includes',
  '/wp-includes/js',
  '/wp-includes/js/jquery',
  '/wp-json',
  '/wp-login.php',
  '/',
  '/wp-login.php',
  '/',
  '/wp-login.php'],
 ['/',
  '/wp-login.php',
  '/wp-admin/load-styles.php',
  '/wp-login.php',
  '/',
  '/wp-login.php',
  '/wp-admin/load-styles.php',
  '/wp-login.php',
  '/wp-content/themes/twentyseventeen/assets/js/global.js',
  '/'],
 ['/wp-content/themes/twentyseventeen/assets/js/jquery.scrollTo.js',
  '/wp-content/themes/twentyseventeen/assets/js/skip-link-focus-fix.js',
  '/wp-content/themes/twentyseventeen/style.css',
  '/wp-admin/load-styles.php',
  '/wp-login.php',
  '/wp-content/themes/twentyseventeen/assets/js/global.js',
  '/wp-includes/js/jquery/jquery-migrate.min.js',
  '/wp-content/themes/twentyseventeen/assets/js/jquery.scrollTo.js',
  '/wp-content/themes/twentyseventeen/assets/js/skip-link-focus-fix.js',
  '/wp-content/themes/twentyseventeen/style.css'],
 ['/wp-admin/load-styles.php',
  '/wp-login.php',
  '/wp-content/themes/twentyseventeen/assets/js/global.js',
  '/wp-includes/js/jquery/jquery-migrate.min.js',
  '/xmlrpc.php',
  '/wp-includes/js/wp-embed.min.js',
  '/wp-login.php',
  '/wp-includes/js/jquery/jquery.js',
  '/wp-content/themes/twentyseventeen/assets/js/jquery.scrollTo.js',
  '/wp-content/themes/twentyseventeen/assets/js/skip-link-focus-fix.js'],
 ['/wp-content/themes/twentyseventeen/style.css',
  '/wp-admin/load-styles.php',
  '/wp-login.php',
  '/wp-content/themes/twentyseventeen/assets/js/global.js',
  '/wp-includes/js/jquery/jquery-migrate.min.js',
  '/xmlrpc.php',
  '/wp-includes/js/wp-embed.min.js',
  '/wp-login.php',
  '/wp-includes/js/jquery/jquery.js',
  '/wp-content/themes/twentyseventeen/assets/js/jquery.scrollTo.js'],
 ['/wp-content/themes/twentyseventeen/assets/js/skip-link-focus-fix.js',
  '/wp-content/themes/twentyseventeen/style.css',
  '/wp-content/themes/twentyseventeen/assets/js/global.js',
  '/xmlrpc.php',
  '/wp-includes/js/jquery/jquery-migrate.min.js',
  '/wp-includes/js/wp-embed.min.js',
  '/wp-login.php',
  '/wp-includes/js/jquery/jquery.js',
  '/wp-content/themes/twentyseventeen/assets/js/jquery.scrollTo.js',
  '/wp-content/themes/twentyseventeen/assets/js/skip-link-focus-fix.js'],
 ['/wp-content/themes/twentyseventeen/style.css',
  '/xmlrpc.php',
  '/wp-includes/js/jquery/jquery-migrate.min.js',
  '/wp-includes/js/wp-embed.min.js',
  '/wp-login.php',
  '/wp-includes/js/jquery/jquery.js',
  '/xmlrpc.php',
  '/wp-includes/js/wp-embed.min.js',
  '/wp-login.php',
  '/wp-includes/js/jquery/jquery.js'],
 ['/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-admin/load-styles.php',
  '/wp-login.php',
  '/wp-admin/load-styles.php',
  '/wp-login.php',
  '/wp-admin/load-styles.php'],
 ['/wp-login.php',
  '/wp-admin/load-styles.php',
  '/wp-login.php',
  '/wp-admin/load-styles.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php'],
 ['/wp-admin/load-styles.php',
  '/wp-login.php',
  '/wp-admin/load-styles.php',
  '/wp-login.php',
  '/wp-admin/load-styles.php',
  '/wp-login.php',
  '/wp-admin/load-styles.php',
  '/wp-login.php',
  '/wp-admin/load-styles.php',
  '/wp-login.php'],
 ['/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-admin/load-styles.php',
  '/wp-admin/load-styles.php',
  '/wp-admin/load-styles.php',
  '/wp-admin/load-styles.php',
  '/wp-admin/load-styles.php'],
 ['/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php',
  '/wp-login.php'],
 ['/WEB-INF/web.xml',
  '/2018',
  '/wp-login.php',
  '/wp-login.php',
  '/',
  '/2018/08',
  '/',
  '/',
  '/2018/08/07',
  '/WEB-INF/applicationContext.xml'],
 ['/2018/08/07/hello-world',
  '/category',
  '/category/uncategorized',
  '/comments',
  '/comments/feed',
  '/WEB-INF/classes/gmpg/org.class',
  '/feed',
  '/WEB-INF/classes/html/className.class',
  '/wp-admin',
  '/WEB-INF/classes/html/className/replace.class'],
 ['/wp-content',
  '/WEB-INF/classes/document/documentElement.class',
  '/wp-content/themes',
  '/WEB-INF/classes/fonts/googleapis/com.class',
  '/wp-content/themes/twentyseventeen',
  '/WEB-INF/classes/s/w/org.class',
  '/wp-admin/load-styles.php',
  '/WEB-INF/classes/fonts/gstatic/com.class',
  '/wp-content/themes/twentyseventeen/assets',
  '/WEB-INF/classes/window/_wpemojiSettings.class'],
 ['/wp-content/themes/twentyseventeen/assets/images',
  '/wp-content/themes/twentyseventeen/A.style.css,qver=4.9.8.pagespeed.cf.COU0KFbmw7.css',
  '/WEB-INF/classes/172/20/254/141.class',
  '/wp-content/themes/twentyseventeen/assets/js',
  '/WEB-INF/classes/release/min/js.class',
  '/wp-includes',
  '/WEB-INF/classes/4/9/8.class',
  '/wp-includes/js',
  '/WEB-INF/classes/String/fromCharCode.class',
  '/wp-includes/js/jquery'],
 ['/wp-content/themes/twentyseventeen/style.css',
  '/WEB-INF/classes/l/clearRect.class',
  '/wp-json',
  '/WEB-INF/classes/k/width.class',
  '/wp-includes/wlwmanifest.xml',
  '/WEB-INF/classes/k/height.class',
  '/wp-login.php',
  '/wp-login.php',
  '/xmlrpc.php',
  '/WEB-INF/classes/l/fillText.class'],
 ['/WEB-INF/classes/c/apply.class',
  '/WEB-INF/classes/k/toDataURL.class',
  '/WEB-INF/classes/l/textBaseline.class',
  '/WEB-INF/classes/l/font.class',
  '/WEB-INF/classes/b/createElement.class',
  '/WEB-INF/classes/c/src.class',
  '/WEB-INF/classes/c/defer.class',
  '/WEB-INF/classes/c/type.class',
  '/WEB-INF/classes/b/getElementsByTagName.class',
  '/WEB-INF/classes/k/getContext.class'],
 ['/WEB-INF/classes/c/supports.class',
  '/WEB-INF/classes/j/length.class',
  '/WEB-INF/classes/c/supports/everything.class',
  '/WEB-INF/classes/c/supports/everythingExceptFlag.class',
  '/WEB-INF/classes/c/supports/flag.class',
  '/WEB-INF/classes/c/DOMReady.class',
  '/WEB-INF/classes/c/readyCallback.class',
  '/WEB-INF/classes/b/addEventListener.class',
  '/WEB-INF/classes/a/addEventListener.class',
  '/WEB-INF/classes/a/attachEvent.class'],
 ['/WEB-INF/classes/b/attachEvent.class',
  '/WEB-INF/classes/b/readyState.class',
  '/WEB-INF/classes/c/source.class',
  '/WEB-INF/classes/g/concatemoji.class',
  '/WEB-INF/classes/g/wpemoji.class',
  '/WEB-INF/classes/g/twemoji.class',
  '/WEB-INF/classes/img/wp.class',
  '/WEB-INF/classes/img/emoji.class',
  '/WEB-INF/classes/0/1em.class',
  '/WEB-INF/classes/style/css.class'],
 ['/WEB-INF/classes/ie8/css.class',
  '/WEB-INF/classes/1/0.class',
  '/WEB-INF/classes/html5/js.class',
  '/WEB-INF/classes/3/7/3.class',
  '/WEB-INF/classes/jquery/js.class',
  '/WEB-INF/classes/1/12/4.class',
  '/WEB-INF/classes/migrate/min/js.class',
  '/WEB-INF/classes/1/4/1.class',
  '/WEB-INF/classes/api/w/org.class',
  '/WEB-INF/classes/xmlrpc/php.class'],
 ['/WEB-INF/classes/wlwmanifest/xml.class',
  '/WEB-INF/classes/header/jpg.class',
  '/WEB-INF/classes/wordpress/org.class',
  '/WEB-INF/classes/fix/js.class',
  '/WEB-INF/classes/global/js.class',
  '/WEB-INF/classes/jquery/scrollTo/js.class',
  '/WEB-INF/classes/2/1/2.class',
  '/WEB-INF/classes/embed/min/js.class',
  '/WEB-INF/classes/1/1.class',
  '/WEB-INF/classes/www/w3/org.class'],
 ['/WEB-INF/classes/6/054h.class',
  '/WEB-INF/classes/9/125v2/214h9/125v.class',
  '/WEB-INF/classes/2/214zM28/5.class',
  '/WEB-INF/classes/13/661q.class',
  '/WEB-INF/classes/1/607.class',
  '/WEB-INF/classes/2/607.class',
  '/WEB-INF/classes/0/938t.class',
  '/WEB-INF/classes/1/107.class',
  '/WEB-INF/classes/2/545h7/286q.class',
  '/WEB-INF/classes/0/321.class'],
 ['/WEB-INF/classes/3/482.class',
  '/WEB-INF/classes/3/571.class',
  '/WEB-INF/classes/3/482zM28/786.class',
  '/WEB-INF/classes/24/107q1/125.class',
  '/WEB-INF/classes/2/179.class',
  '/WEB-INF/classes/0/571t1/357.class',
  '/WEB-INF/classes/1/554h3/946q.class',
  '/WEB-INF/classes/1/786.class',
  '/WEB-INF/classes/5/482.class',
  '/WEB-INF/classes/7/625.class'],
 ['/WEB-INF/classes/3/821.class',
  '/WEB-INF/classes/6/080.class',
  '/WEB-INF/classes/2/357t.class',
  '/WEB-INF/classes/2/259.class',
  '/WEB-INF/classes/6/196q0.class',
  '/WEB-INF/classes/3/714.class',
  '/WEB-INF/classes/2/33.class',
  '/WEB-INF/classes/6/17t6/009.class',
  '/WEB-INF/classes/2/455q2/464.class',
  '/WEB-INF/classes/4/295.class'],
 ['/WEB-INF/classes/1/214t2/732.class',
  '/WEB-INF/classes/3/196.class',
  '/WEB-INF/classes/0/902.class',
  '/WEB-INF/classes/4/429q0.class',
  '/WEB-INF/classes/0/304.class',
  '/WEB-INF/classes/0/036.class',
  '/WEB-INF/classes/0/839h.class',
  '/WEB-INF/classes/11/75q0.class',
  '/WEB-INF/classes/1/982.class',
  '/WEB-INF/classes/1/027.class'],
 ['/WEB-INF/classes/3/063t2/973.class',
  '/WEB-INF/classes/1/080zM4/946.class',
  '/WEB-INF/classes/23/214h5/286q3/661.class',
  '/WEB-INF/classes/3/661.class',
  '/WEB-INF/classes/2/982.class',
  '/WEB-INF/classes/3/214.class',
  '/WEB-INF/classes/3/554.class',
  '/WEB-INF/classes/3/214h.class',
  '/WEB-INF/classes/5/393v6/196zM4/946.class',
  '/WEB-INF/classes/13/625h5/018q1/393.class'],
 ['/WEB-INF/classes/2/205.class',
  '/WEB-INF/classes/0/652t0/813.class',
  '/WEB-INF/classes/2/027q0.class',
  '/WEB-INF/classes/2/571.class',
  '/WEB-INF/classes/3/393.class',
  '/WEB-INF/classes/2/571h.class',
  '/WEB-INF/classes/4/643v5/25zM0.class',
  '/WEB-INF/classes/4/536h10/607q1/554.class',
  '/WEB-INF/classes/2/768.class',
  '/WEB-INF/classes/0/25t2/259.class'],
 ['/WEB-INF/classes/0/848.class',
  '/WEB-INF/classes/1/723.class',
  '/WEB-INF/classes/0/563.class',
  '/WEB-INF/classes/2/75q0.class',
  '/WEB-INF/classes/3/232.class',
  '/WEB-INF/classes/3/071.class',
  '/WEB-INF/classes/4/696.class',
  '/WEB-INF/classes/2/036.class',
  '/WEB-INF/classes/0/571.class',
  '/WEB-INF/classes/2/054t1/036.class'],
 ['/WEB-INF/classes/3/643q0.class',
  '/WEB-INF/classes/1/339.class',
  '/WEB-INF/classes/0/438.class',
  '/WEB-INF/classes/2/438t.class',
  '/WEB-INF/classes/1/179.class',
  '/WEB-INF/classes/1/848.class',
  '/WEB-INF/classes/1/759.class',
  '/WEB-INF/classes/1/268.class',
  '/WEB-INF/classes/2/161.class',
  '/WEB-INF/classes/0/75.class'],
 ['/WEB-INF/classes/2/393.class',
  '/WEB-INF/classes/0/232h.class',
  '/WEB-INF/classes/10/911v.class',
  '/WEB-INF/classes/22/5z.class',
  '/WEB-INF/classes/M18/286.class',
  '/WEB-INF/classes/5/411l.class',
  '/WEB-INF/classes/5/411.class',
  '/WEB-INF/classes/10/393.class',
  '/WEB-INF/classes/0/429.class',
  '/WEB-INF/classes/0/554h4/982v7/411h.class'],
 ['/WEB-INF/classes/9/054l.class',
  '/WEB-INF/classes/0/786.class',
  '/WEB-INF/classes/0/536.class',
  '/WEB-INF/classes/2/536.class',
  '/WEB-INF/classes/4/875.class',
  '/WEB-INF/classes/0/536h.class',
  '/WEB-INF/classes/5/375v.class',
  '/WEB-INF/classes/5/411l5/411.class',
  '/WEB-INF/classes/10/411.class',
  '/WEB-INF/classes/4/982v.class'],
 ['/WEB-INF/classes/7/411h9/054l0/786.class',
  '/WEB-INF/classes/0/536h5/375v5/411z.class',
  '/WEB-INF/classes/M10/661.class',
  '/WEB-INF/classes/7/518v20/946q0.class',
  '/WEB-INF/classes/0/446.class',
  '/WEB-INF/classes/0/223.class',
  '/WEB-INF/classes/0/759t.class',
  '/WEB-INF/classes/0/652.class',
  '/WEB-INF/classes/0/313q.class',
  '/WEB-INF/classes/0/589.class'],
 ['/WEB-INF/classes/0/143l.class',
  '/WEB-INF/classes/8/304.class',
  '/WEB-INF/classes/4/161q.class',
  '/WEB-INF/classes/0/375.class',
  '/WEB-INF/classes/0/179.class',
  '/WEB-INF/classes/0/634.class',
  '/WEB-INF/classes/0/598t.class',
  '/WEB-INF/classes/0/259.class',
  '/WEB-INF/classes/0/83v.class',
  '/WEB-INF/classes/20/357q0.class'],
 ['/WEB-INF/classes/0/357.class',
  '/WEB-INF/classes/0/607t0/518.class',
  '/WEB-INF/classes/0/25q0/25.class',
  '/WEB-INF/classes/0/268l9/125.class',
  '/WEB-INF/classes/4/571q0/054.class',
  '/WEB-INF/classes/0/054.class',
  '/WEB-INF/classes/0/089zM11/804.class',
  '/WEB-INF/classes/9/321l9/536.class',
  '/WEB-INF/classes/15/464.class',

In [5]:
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
te_ary = te.fit(paths_matrix).transform(paths_matrix)
df = pd.DataFrame(te_ary, columns=te.columns_)

df

,/,/%00,/%00/,"/%0a%0a<script>alert(\""Vulnerable\"")</script>.jsp",/%22%3cscript%3ealert(%22xss%22)%3c/script%3e,/%2E%2E/%2E%2E/%2E%2E/%2E%2E/%2E%2E/windows/win.ini,/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/passwd,/%2e/,/%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2fetc%2fpasswd,/%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f../boot.ini,...,/zipfiles/,/zm/,/zorum/index.php,/zw/,/~/<script>alert('Vulnerable')</script>.asp,/~/<script>alert('Vulnerable')</script>.aspx,/~/index.html,/~nobody/etc/passwd,/~root,/~root/
0,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1141,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1142,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1143,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1144,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1145,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [9]:
from mlxtend.frequent_patterns import apriori

apriori(df, use_colnames=True, min_support=0.05)

      support                                           itemsets
0    0.172775                                                (/)
1    0.198080                        (/wp-admin/load-styles.php)
2    0.100349  (/wp-content/themes/twentyseventeen/assets/js/...
3    0.102967  (/wp-content/themes/twentyseventeen/assets/js/...
4    0.103839  (/wp-content/themes/twentyseventeen/assets/js/...
..        ...                                                ...
97   0.055846  (/wp-content/themes/twentyseventeen/style.css,...
98   0.065445  (/wp-includes/js/wp-embed.min.js, /wp-login.ph...
99   0.054101  (/wp-login.php, /wp-includes/js/jquery/jquery-...
100  0.055846  (/wp-includes/js/wp-embed.min.js, /wp-login.ph...
101  0.059337  (/wp-includes/js/wp-embed.min.js, /wp-login.ph...

[102 rows x 2 columns]