In [2]:
import pandas as pd

df = pd.read_csv("../detected.csv")

df.head(5)

,timestamp,method,path,status,ip,port,uuid,sess_uuid,detection_name,detection_type,user_agent,referer,attack_name,attack_type
0,2025-05-22T07:53:51.660458,GET,/,200,172.18.0.1,38158,5da851cd-09cc-4bb7-a200-f07dad1a8897,e906dd52-8d43-4894-98e0-3b6b93073434,index,1,curl/7.81.0,NaN,Unknown,0
1,2025-05-22T07:54:41.725206,GET,/,200,172.18.0.1,51798,5da851cd-09cc-4bb7-a200-f07dad1a8897,4071c0d0-c143-4171-9d72-57001462d87e,index,1,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,NaN,Unknown,0
2,2025-05-22T07:54:41.929057,GET,/stylesheets/jquery/jquery-ui-1.11.0.css?15286...,200,172.18.0.1,51806,5da851cd-09cc-4bb7-a200-f07dad1a8897,c959aef7-3a6f-4f11-8898-6c8402172368,index,1,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,http://localhost/,Unknown,0
3,2025-05-22T07:54:42.114829,GET,/stylesheets/application.css?1528612569,200,172.18.0.1,51812,5da851cd-09cc-4bb7-a200-f07dad1a8897,c959aef7-3a6f-4f11-8898-6c8402172368,index,1,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,http://localhost/,Unknown,0
4,2025-05-22T07:54:42.131187,GET,/stylesheets/responsive.css?1528612569,200,172.18.0.1,51826,5da851cd-09cc-4bb7-a200-f07dad1a8897,c959aef7-3a6f-4f11-8898-6c8402172368,index,1,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,http://localhost/,Unknown,0

In [3]:
filtered_df = df[df['user_agent'] == "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"]

# get the paths with params
# filtered_paths = filtered_df["path"]

# get the paths without params
filtered_paths = filtered_df["path"].apply(lambda x: x.split('?', 1)[0])

filtered_paths_matrix = []
tmp = []

for i, x in enumerate(filtered_paths):
  if i % 10 == 0 and i != 0:
    filtered_paths_matrix.append(tmp)
    tmp = []
  tmp.append(x)

# Add the last group if not empty
if tmp:
  filtered_paths_matrix.append(tmp)

filtered_paths_matrix

[['/',
  '/',
  '/sitemap.xml',
  '/robots.txt',
  '/account/register',
  '/',
  '/login',
  '/projects',
  '/search',
  '/projects'],
 ['/favicon.ico',
  '/projects',
  '/news.atom',
  '/stylesheets/jquery/jquery-ui-1.11.0.css',
  '/stylesheets/responsive.css',
  '/stylesheets/application.css',
  '/activity.atom',
  '/javascripts/jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js',
  '/javascripts/application.js',
  '/account/lost_password'],
 ['/javascripts/responsive.js',
  '/search',
  '/projects',
  '/time_entries',
  '/issues/gantt',
  '/activity',
  '/issues',
  '/search',
  '/news',
  '/login'],
 ['/projects',
  '/issues/calendar',
  '/account/register',
  '/projects',
  '/search',
  '/projects.atom',
  '/account/lost_password',
  '/projects',
  '/activity',
  '/projects'],
 ['/activity',
  '/activity',
  '/projects',
  '/activity',
  '/activity',
  '/activity',
  '/issues',
  '/time_entries/report',
  '/time_entries',
  '/issues/gantt'],
 ['/issues/gantt',
  '/activity',
  '/activity',
  '/issues/gantt',
  '/activity',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt'],
 ['/issues/gantt',
  '/issues/gantt',
  '/issues.atom',
  '/issues/gantt',
  '/issues/gantt.png',
  '/issues/gantt.pdf',
  '/time_entries.atom',
  '/projects',
  '/issues',
  '/issues.csv'],
 ['/issues.pdf',
  '/projects',
  '/stylesheets/scm.css',
  '/issues/changes.atom',
  '/javascripts/raphael.js',
  '/stylesheets/context_menu.css',
  '/javascripts/gantt.js',
  '/search',
  '/javascripts/context_menu.js',
  '/search'],
 ['/activity',
  '/time_entries',
  '/projects',
  '/issues/calendar',
  '/issues/calendar',
  '/issues/gantt',
  '/search',
  '/issues/calendar',
  '/issues',
  '/search'],
 ['/issues.csv',
  '/issues/calendar',
  '/activity',
  '/activity.atom',
  '/activity',
  '/activity.atom',
  '/activity',
  '/activity',
  '/activity.atom',
  '/activity.atom'],
 ['/activity',
  '/activity.atom',
  '/activity',
  '/activity.atom',
  '/issues.atom',
  '/issues.csv',
  '/issues.pdf',
  '/time_entries/report',
  '/time_entries/report',
  '/issues/gantt'],
 ['/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt.pdf'],
 ['/issues/gantt.png',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt'],
 ['/issues/gantt.pdf',
  '/issues/gantt',
  '/activity.atom',
  '/activity',
  '/issues/gantt.png',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity.atom'],
 ['/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt.pdf',
  '/issues/gantt.png',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt'],
 ['/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt.pdf',
  '/issues/gantt.png',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt'],
 ['/issues/gantt.pdf',
  '/issues/gantt.png',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt.pdf',
  '/issues/gantt.png',
  '/issues/gantt'],
 ['/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt.png',
  '/issues/gantt.pdf',
  '/issues/gantt',
  '/issues/gantt'],
 ['/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt.pdf',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt.png',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt'],
 ['/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt.pdf',
  '/issues/gantt.png',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt.pdf',
  '/issues/gantt.png',
  '/issues/gantt'],
 ['/issues/gantt',
  '/issues/calendar',
  '/issues/calendar',
  '/issues/calendar',
  '/issues/calendar',
  '/issues/calendar',
  '/issues/calendar',
  '/issues/calendar',
  '/5915742981782352343',
  '/account/7223784796158722350'],
 ['/issues/1138171552812458108',
  '/javascripts/6727623619620638621',
  '/stylesheets/4065296821106598122',
  '/stylesheets/jquery/2546093590119171156',
  '/time_entries/1484562887745712461',
  '/account',
  '/activity',
  '/activity',
  '/activity',
  '/login'],
 ['/account/lost_password',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/account/register'],
 ['/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity.atom',
  '/activity',
  '/activity',
  '/activity',
  '/activity'],
 ['/activity',
  '/account/lost_password',
  '/login',
  '/account/register',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity.atom'],
 ['/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity.atom'],
 ['/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/account/lost_password',
  '/login',
  '/account/register',
  '/activity',
  '/activity'],
 ['/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity.atom',
  '/activity',
  '/activity',
  '/activity',
  '/activity'],
 ['/activity',
  '/activity',
  '/activity.atom',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/account/lost_password'],
 ['/login',
  '/account/register',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity'],
 ['/activity',
  '/activity.atom',
  '/activity',
  '/activity',
  '/activity',
  '/activity.atom',
  '/activity',
  '/activity',
  '/activity',
  '/activity'],
 ['/activity',
  '/activity',
  '/activity',
  '/account/lost_password',
  '/login',
  '/account/register',
  '/activity',
  '/activity',
  '/activity.atom',
  '/activity'],
 ['/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity.atom',
  '/activity',
  '/activity',
  '/activity'],
 ['/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/account/lost_password',
  '/login',
  '/account/register'],
 ['/activity',
  '/activity',
  '/activity.atom',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity'],
 ['/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity.atom',
  '/activity',
  '/activity'],
 ['/activity',
  '/account/lost_password',
  '/login',
  '/account/register',
  '/activity',
  '/activity.atom',
  '/activity',
  '/activity',
  '/activity',
  '/activity'],
 ['/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity.atom'],
 ['/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/account/lost_password',
  '/login',
  '/account/register',
  '/activity',
  '/activity.atom'],
 ['/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity.atom',
  '/activity',
  '/activity'],
 ['/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/account/lost_password'],
 ['/login',
  '/account/register',
  '/activity.atom',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity.atom'],
 ['/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity'],
 ['/activity',
  '/activity',
  '/activity',
  '/account/lost_password',
  '/login',
  '/account/register',
  '/activity.atom',
  '/activity',
  '/activity',
  '/activity'],
 ['/activity',
  '/activity',
  '/activity',
  '/activity.atom',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity'],
 ['/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/account/lost_password',
  '/login',
  '/account/register'],
 ['/activity.atom',
  '/activity',
  '/activity',
  '/activity',
  '/account/lost_password',
  '/activity',
  '/activity',
  '/activity',
  '/activity.atom',
  '/activity'],
 ['/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity'],
 ['/activity',
  '/activity',
  '/login',
  '/account/register',
  '/activity.atom',
  '/account/lost_password',
  '/activity',
  '/activity',
  '/activity',
  '/activity'],
 ['/activity.atom',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity'],
 ['/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/login',
  '/activity.atom',
  '/account/register',
  '/account/lost_password'],
 ['/activity',
  '/activity',
  '/activity',
  '/activity.atom',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity'],
 ['/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity'],
 ['/login',
  '/activity.atom',
  '/account/register',
  '/account/lost_password',
  '/activity',
  '/activity',
  '/activity',
  '/activity.atom',
  '/login',
  '/activity'],
 ['/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity'],
 ['/activity',
  '/activity',
  '/activity.atom',
  '/activity',
  '/activity',
  '/activity',
  '/account/register',
  '/account/lost_password',
  '/activity',
  '/activity'],
 ['/login',
  '/activity.atom',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity'],
 ['/activity',
  '/activity',
  '/activity',
  '/activity.atom',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity'],
 ['/account/register',
  '/account/lost_password',
  '/activity',
  '/activity',
  '/login',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity'],
 ['/activity',
  '/activity.atom',
  '/activity',
  '/activity.atom',
  '/account/register',
  '/activity.atom',
  '/activity.atom',
  '/activity.atom',
  '/activity.atom',
  '/favicon.ico'],
 ['/activity',
  '/account/lost_password',
  '/activity',
  '/activity',
  '/login',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity'],
 ['/activity.atom',
  '/activity',
  '/activity.atom',
  '/activity',
  '/account/register',
  '/activity.atom',
  '/activity.atom',
  '/activity.atom',
  '/activity.atom',
  '/favicon.ico'],
 ['/issues/calendar',
  '/issues/calendar',
  '/issues/calendar',
  '/issues/calendar',
  '/activity',
  '/account/lost_password',
  '/activity',
  '/activity',
  '/login',
  '/activity'],
 ['/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity.atom',
  '/activity',
  '/activity.atom',
  '/activity',
  '/account/register',
  '/activity.atom'],
 ['/activity.atom',
  '/activity.atom',
  '/activity.atom',
  '/favicon.ico',
  '/issues/calendar',
  '/issues/calendar',
  '/issues/calendar',
  '/issues/calendar',
  '/activity',
  '/account/lost_password'],
 ['/activity',
  '/activity',
  '/login',
  '/activity',
  '/activity',
  '/activity',
  '/activity.atom',
  '/account/register',
  '/activity',
  '/activity'],
 ['/activity',
  '/activity',
  '/activity.atom',
  '/activity.atom',
  '/activity.atom',
  '/activity.atom',
  '/activity.atom',
  '/favicon.ico',
  '/issues/calendar',
  '/issues/calendar'],
 ['/issues/calendar',
  '/issues/calendar',
  '/activity',
  '/account/lost_password',
  '/activity',
  '/activity',
  '/login',
  '/activity',
  '/activity',
  '/activity'],
 ['/activity.atom',
  '/account/register',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity.atom',
  '/activity.atom',
  '/activity.atom',
  '/favicon.ico'],
 ['/issues/calendar',
  '/activity.atom',
  '/activity.atom',
  '/issues/calendar',
  '/issues/calendar',
  '/issues/calendar',
  '/activity',
  '/account/lost_password',
  '/activity',
  '/activity'],
 ['/login',
  '/activity',
  '/activity',
  '/activity.atom',
  '/activity',
  '/account/register',
  '/activity',
  '/activity',
  '/activity',
  '/activity'],
 ['/activity.atom',
  '/activity.atom',
  '/activity.atom',
  '/favicon.ico',
  '/activity.atom',
  '/activity.atom',
  '/issues/calendar',
  '/issues/calendar',
  '/issues/calendar',
  '/issues/calendar'],
 ['/activity',
  '/account/lost_password',
  '/activity',
  '/activity',
  '/login',
  '/activity',
  '/activity',
  '/activity.atom',
  '/activity',
  '/account/register'],
 ['/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity.atom',
  '/activity.atom',
  '/activity.atom',
  '/activity.atom',
  '/favicon.ico',
  '/issues/calendar'],
 ['/issues/calendar',
  '/activity.atom',
  '/issues/calendar',
  '/issues/calendar',
  '/activity',
  '/account/lost_password',
  '/activity',
  '/activity',
  '/login',
  '/activity'],
 ['/activity.atom',
  '/activity',
  '/account/register',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity.atom',
  '/activity.atom'],
 ['/activity.atom',
  '/issues/calendar',
  '/activity.atom',
  '/favicon.ico',
  '/activity.atom',
  '/issues/calendar',
  '/issues/calendar',
  '/issues/calendar',
  '/account/lost_password',
  '/activity'],
 ['/activity',
  '/activity',
  '/login',
  '/activity.atom',
  '/activity',
  '/activity',
  '/account/register',
  '/activity',
  '/activity',
  '/activity'],
 ['/activity',
  '/activity.atom',
  '/activity.atom',
  '/activity',
  '/activity.atom',
  '/activity.atom',
  '/issues/calendar',
  '/activity.atom',
  '/favicon.ico',
  '/issues/calendar'],
 ['/issues/calendar',
  '/account/lost_password',
  '/issues/calendar',
  '/activity',
  '/activity',
  '/activity',
  '/login',
  '/activity',
  '/activity.atom',
  '/account/register'],
 ['/activity',
  '/activity',
  '/activity',
  '/activity',
  '/activity.atom',
  '/activity',
  '/activity.atom',
  '/activity.atom',
  '/activity.atom',
  '/activity'],
 ['/issues/calendar',
  '/activity.atom',
  '/account/lost_password',
  '/favicon.ico',
  '/issues/calendar',
  '/issues/calendar',
  '/issues/calendar',
  '/activity',
  '/activity',
  '/activity'],
 ['/login',
  '/account/register',
  '/account/lost_password',
  '/activity',
  '/activity.atom',
  '/activity',
  '/activity',
  '/activity',
  '/activity.atom',
  '/activity.atom'],
 ['/activity',
  '/activity',
  '/activity.atom',
  '/activity.atom',
  '/activity.atom',
  '/activity',
  '/issues/calendar',
  '/favicon.ico',
  '/issues/calendar',
  '/issues/calendar'],
 ['/issues/calendar',
  '/activity',
  '/activity',
  '/login',
  '/activity',
  '/account/register',
  '/account/lost_password',
  '/activity.atom',
  '/activity',
  '/activity'],
 ['/activity',
  '/activity',
  '/activity.atom',
  '/activity.atom',
  '/activity.atom',
  '/activity',
  '/activity',
  '/activity.atom',
  '/activity.atom',
  '/activity'],
 ['/issues/calendar',
  '/issues/calendar',
  '/favicon.ico',
  '/activity',
  '/activity',
  '/issues/calendar',
  '/issues/calendar',
  '/login',
  '/account/register',
  '/activity'],
 ['/account/lost_password',
  '/activity.atom',
  '/activity',
  '/activity',
  '/activity',
  '/activity.atom',
  '/activity.atom',
  '/activity',
  '/activity.atom',
  '/activity'],
 ['/activity',
  '/activity.atom',
  '/activity.atom',
  '/activity',
  '/issues/calendar',
  '/issues/calendar',
  '/favicon.ico',
  '/activity',
  '/issues/calendar',
  '/activity'],
 ['/issues/calendar',
  '/login',
  '/account/register',
  '/activity',
  '/account/lost_password',
  '/activity.atom',
  '/activity',
  '/activity',
  '/activity.atom',
  '/activity'],
 ['/activity',
  '/activity.atom',
  '/activity.atom',
  '/activity',
  '/activity',
  '/activity.atom',
  '/favicon.ico',
  '/activity',
  '/issues/calendar',
  '/activity'],
 ['/issues/calendar',
  '/activity',
  '/activity.atom',
  '/issues/calendar',
  '/issues/calendar',
  '/login',
  '/account/register',
  '/activity',
  '/account/lost_password',
  '/activity.atom'],
 ['/activity',
  '/activity.atom',
  '/activity',
  '/activity.atom',
  '/activity',
  '/issues/calendar',
  '/activity.atom',
  '/activity.atom',
  '/favicon.ico',
  '/activity.atom'],
 ['/activity',
  '/activity',
  '/issues/calendar',
  '/activity',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/calendar',
  '/issues/gantt',
  '/issues/calendar',
  '/login'],
 ['/account/register',
  '/account/lost_password',
  '/activity',
  '/favicon.ico',
  '/login',
  '/account/register',
  '/issues/calendar',
  '/issues/calendar',
  '/account/lost_password',
  '/activity'],
 ['/issues/gantt',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt.pdf',
  '/issues/gantt.png',
  '/issues/gantt.png',
  '/issues',
  '/issues',
  '/issues/gantt',
  '/issues.atom'],
 ['/issues/gantt.pdf',
  '/issues/calendar',
  '/issues/calendar',
  '/issues/gantt',
  '/issues',
  '/login',
  '/account/register',
  '/activity',
  '/favicon.ico',
  '/account/lost_password'],
 ['/issues/calendar',
  '/issues/calendar',
  '/activity',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt.pdf',
  '/issues/gantt',
  '/issues/gantt.png',
  '/issues',
  '/issues/gantt.png'],
 ['/issues/gantt.pdf',
  '/issues.atom',
  '/issues/calendar',
  '/issues',
  '/issues/gantt',
  '/issues/gantt',
  '/issues',
  '/issues.csv',
  '/issues.csv',
  '/login'],
 ['/account/register',
  '/account/lost_password',
  '/activity',
  '/favicon.ico',
  '/issues/calendar',
  '/issues/calendar',
  '/activity',
  '/issues/gantt',
  '/issues/gantt.pdf',
  '/issues/gantt.png'],
 ['/issues/gantt',
  '/issues/gantt',
  '/issues/gantt.pdf',
  '/issues/gantt.png',
  '/issues.atom',
  '/issues',
  '/issues/calendar',
  '/issues/gantt',
  '/issues',
  '/issues/gantt'],
 ['/issues',
  '/issues.csv',
  '/issues.csv',
  '/login',
  '/account/register',
  '/account/lost_password',
  '/issues/calendar',
  '/activity',
  '/issues/calendar',
  '/activity'],
 ['/issues/gantt',
  '/issues/gantt.png',
  '/issues/gantt.pdf',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/gantt.pdf',
  '/issues/gantt.png',
  '/issues/calendar',
  '/issues',
  '/issues/gantt'],
 ['/issues/gantt',
  '/issues',
  '/issues.atom',
  '/issues.csv',
  '/issues.csv',
  '/issues',
  '/login',
  '/account/register',
  '/account/lost_password',
  '/javascripts'],
 ['/issues/calendar',
  '/activity',
  '/issues/calendar',
  '/activity',
  '/issues/gantt.png',
  '/issues/gantt',
  '/issues.pdf',
  '/issues/gantt.pdf',
  '/issues/calendar',
  '/issues/gantt'],
 ['/issues/gantt.png',
  '/issues/gantt',
  '/issues',
  '/issues.csv',
  '/issues/gantt',
  '/issues/gantt',
  '/issues',
  '/issues.csv',
  '/issues.atom',
  '/issues'],
 ['/issues/gantt.pdf',
  '/login',
  '/account/register',
  '/account/lost_password',
  '/issues/calendar',
  '/activity',
  '/issues/calendar',
  '/activity',
  '/issues/gantt.png',
  '/issues/gantt'],
 ['/issues.pdf',
  '/issues/gantt.pdf',
  '/issues/gantt',
  '/issues.csv',
  '/issues/gantt',
  '/issues',
  '/issues/gantt',
  '/issues/gantt',
  '/issues/calendar',
  '/issues.atom'],
 ['/issues',
  '/issues.csv',
  '/issues/gantt.png',
  '/issues/gantt.pdf',
  '/issues',
  '/login',
  '/account/register',
  '/account/lost_password',
  '/activity',
  '/issues/gantt.png'],
 ['/activity',
  '/issues/calendar',
  '/issues/calendar',
  '/issues/gantt',
  '/issues.pdf',
  '/issues/gantt.pdf',
  '/issues.csv',
  '/issues/gantt',
  '/issues',
  '/issues/calendar'],
 ['/issues/gantt',
  '/issues/gantt',

In [4]:
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
te_ary = te.fit(filtered_paths_matrix).transform(filtered_paths_matrix)
df = pd.DataFrame(te_ary, columns=te.columns_)

df

,/,/.DS_Store,/._darcs,/.bzr,/.env,/.git/config,/.hg,/.htaccess,/.idea/WebServers.xml,/.php_cs.cache,...,/time_entries/.htaccess,/time_entries/1484562887745712461,/time_entries/report,/time_entries/report/,/time_entries/trace.axd,/trace.axd,/vb_test.php,/vim_settings.xml,/winscp.ini,/ws_ftp.ini
0,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3321,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3322,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3323,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3324,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3325,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [5]:
from mlxtend.frequent_patterns import apriori

apriori(df, use_colnames=True, min_support=0.2)

     support                                       itemsets
0   0.300661                       (/account/lost_password)
1   0.522850                            (/account/register)
2   0.645219                                    (/activity)
3   0.382742                                      (/issues)
4   0.292844                                  (/issues.csv)
5   0.279014                             (/issues/calendar)
6   0.579675                                (/issues/gantt)
7   0.291040                            (/issues/gantt.pdf)
8   0.291942                            (/issues/gantt.png)
9   0.371016                                       (/login)
10  0.516837                                      (/search)
11  0.229705                                (/time_entries)
12  0.265183                         (/time_entries/report)
13  0.209561    (/account/register, /account/lost_password)
14  0.217980            (/account/lost_password, /activity)
15  0.207757               (/login, /account/lost_password)
16  0.328623                 (/account/register, /activity)
17  0.302465             (/account/register, /issues/gantt)
18  0.259170                    (/account/register, /login)
19  0.298857                   (/account/register, /search)
20  0.261876                           (/issues, /activity)
21  0.381539                     (/issues/gantt, /activity)
22  0.266687                            (/login, /activity)
23  0.288635                           (/activity, /search)
24  0.340950                       (/issues, /issues/gantt)
25  0.214071                             (/issues, /search)
26  0.250451                   (/issues/gantt, /issues.csv)
27  0.248647             (/issues/gantt, /issues/gantt.pdf)
28  0.243836             (/issues/gantt, /issues/gantt.png)
29  0.220986                        (/login, /issues/gantt)
30  0.356284                       (/issues/gantt, /search)
31  0.210463                       (/time_entries, /search)
32  0.247745                (/search, /time_entries/report)
33  0.212568          (/time_entries, /time_entries/report)
34  0.202946  (/account/register, /issues/gantt, /activity)
35  0.201443    (/account/register, /issues/gantt, /search)
36  0.235418            (/issues, /issues/gantt, /activity)
37  0.250451            (/issues/gantt, /activity, /search)