In [17]:
import pandas as pd

df = pd.read_json("../detected.json", lines=True)

df.head(5)

,method,path,headers,uuid,peer,status,cookies,response_msg,timestamp,post_data
0,GET,/,"{'host': '127.0.0.1', 'user-agent': 'curl/7.81...",eee6754c-7a79-4143-b40a-fb4f6358f230,"{'ip': '172.18.0.1', 'port': 36070}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-14 09:02:40.155204,NaN
1,HEAD,/,"{'host': 'localhost', 'connection': 'Keep-Aliv...",eee6754c-7a79-4143-b40a-fb4f6358f230,"{'ip': '172.18.0.1', 'port': 58816}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-14 09:03:06.043339,NaN
2,GET,/,{'user-agent': 'Mozilla/5.00 (Nikto/2.1.5) (Ev...,eee6754c-7a79-4143-b40a-fb4f6358f230,"{'ip': '172.18.0.1', 'port': 58816}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-14 09:03:06.107540,NaN
3,GET,/,{'user-agent': 'Mozilla/5.00 (Nikto/2.1.5) (Ev...,eee6754c-7a79-4143-b40a-fb4f6358f230,"{'ip': '172.18.0.1', 'port': 58816}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-14 09:03:06.116424,NaN
4,GET,/bTsJgT9V,{'user-agent': 'Mozilla/5.00 (Nikto/2.1.5) (Ev...,eee6754c-7a79-4143-b40a-fb4f6358f230,"{'ip': '172.18.0.1', 'port': 58816}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-14 09:03:06.126323,NaN

In [18]:
attacks = []

for _, row in df.iterrows():
  detection = row.get("response_msg", {}).get("response", {}).get("message", {}).get("detection", {})
  detection_name = detection.get("name", "")
  if detection_name != "index":
    attacks.append(detection_name)

attacks

['cmd_exec',
 'cmd_exec',
 'cmd_exec',
 'cmd_exec',
 'cmd_exec',
 'cmd_exec',
 'cmd_exec',
 'cmd_exec',
 'xss',
 'xss',
 'xss',
 'wp-content',
 'cmd_exec',
 'unknown',
 'unknown',
 'lfi',
 'xss',
 'xss',
 'unknown',
 'xss',
 'cmd_exec',
 'unknown',
 'wp-content',
 'wp-content',
 'wp-content',
 'cmd_exec',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'lfi',
 'xss',
 'xss',
 'sqli',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'xss',
 'cmd_exec',
 'lfi',
 'cmd_exec',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'cmd_exec',
 'cmd_exec',
 'cmd_exec',
 'cmd_exec',
 'cmd_exec',
 'cmd_exec',
 'cmd_exec',
 'cmd_exec',
 'cmd_exec',
 'cmd_exec',
 'lfi',
 'lfi',
 'lfi',
 'lfi',
 'cmd_exec',
 'sqli',
 'sqli',
 'sqli',
 'unknown',
 'unknown',
 'cmd_exec']

In [19]:
attack_matrix = []
tmp = []

for i, x in enumerate(attacks):
  if i % 10 == 0 and i != 0:
    attack_matrix.append(tmp)
    tmp = []
  tmp.append(x)

# Add the last group if not empty
if tmp:
  attack_matrix.append(tmp)

attack_matrix

[['cmd_exec',
  'cmd_exec',
  'cmd_exec',
  'cmd_exec',
  'cmd_exec',
  'cmd_exec',
  'cmd_exec',
  'cmd_exec',
  'xss',
  'xss'],
 ['xss',
  'wp-content',
  'cmd_exec',
  'unknown',
  'unknown',
  'lfi',
  'xss',
  'xss',
  'unknown',
  'xss'],
 ['cmd_exec',
  'unknown',
  'wp-content',
  'wp-content',
  'wp-content',
  'cmd_exec',
  'xss',
  'xss',
  'xss',
  'xss'],
 ['xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss'],
 ['xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss'],
 ['xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss'],
 ['xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss'],
 ['xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss'],
 ['xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss'],
 ['xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss'],
 ['xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss'],
 ['xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss'],
 ['xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss'],
 ['xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss'],
 ['xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss'],
 ['xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss'],
 ['xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss'],
 ['xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss'],
 ['xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss'],
 ['xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss'],
 ['xss', 'xss', 'xss', 'xss', 'lfi', 'xss', 'xss', 'sqli', 'xss', 'xss'],
 ['xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss'],
 ['xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss'],
 ['xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss'],
 ['xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss'],
 ['xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss'],
 ['xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss'],
 ['xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss'],
 ['xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'xss', 'cmd_exec', 'lfi'],
 ['cmd_exec', 'lfi', 'lfi', 'lfi', 'lfi', 'lfi', 'lfi', 'lfi', 'lfi', 'lfi'],
 ['lfi', 'lfi', 'lfi', 'lfi', 'lfi', 'lfi', 'lfi', 'lfi', 'lfi', 'lfi'],
 ['lfi', 'lfi', 'lfi', 'lfi', 'lfi', 'lfi', 'lfi', 'lfi', 'lfi', 'lfi'],
 ['lfi',
  'lfi',
  'cmd_exec',
  'cmd_exec',
  'cmd_exec',
  'cmd_exec',
  'cmd_exec',
  'cmd_exec',
  'cmd_exec',
  'cmd_exec'],
 ['cmd_exec',
  'cmd_exec',
  'lfi',
  'lfi',
  'lfi',
  'lfi',
  'cmd_exec',
  'sqli',
  'sqli',
  'sqli'],
 ['unknown', 'unknown', 'cmd_exec']]

In [20]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, fpmax, fpgrowth

te = TransactionEncoder()
te_ary = te.fit(attack_matrix).transform(attack_matrix)
df = pd.DataFrame(te_ary, columns=te.columns_)

df.head(10)

   cmd_exec    lfi   sqli  unknown  wp-content   xss
0      True  False  False    False       False  True
1      True   True  False     True        True  True
2      True  False  False     True        True  True
3     False  False  False    False       False  True
4     False  False  False    False       False  True
5     False  False  False    False       False  True
6     False  False  False    False       False  True
7     False  False  False    False       False  True
8     False  False  False    False       False  True
9     False  False  False    False       False  True

In [21]:
# frequent_itemsets = fpgrowth(df, min_support=0.3, use_colnames=True)
frequent_itemsets = fpgrowth(df, min_support=0.001, use_colnames=True)
### alternatively:
#frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
#frequent_itemsets = fpmax(df, min_support=0.6, use_colnames=True)

frequent_itemsets.head(20)

     support                       itemsets
0   0.828571                          (xss)
1   0.228571                     (cmd_exec)
2   0.228571                          (lfi)
3   0.085714                      (unknown)
4   0.057143                   (wp-content)
5   0.057143                         (sqli)
6   0.114286                (cmd_exec, xss)
7   0.142857                (cmd_exec, lfi)
8   0.085714                     (xss, lfi)
9   0.057143           (cmd_exec, xss, lfi)
10  0.085714            (cmd_exec, unknown)
11  0.057143                 (unknown, xss)
12  0.028571                 (unknown, lfi)
13  0.057143       (cmd_exec, unknown, xss)
14  0.028571       (cmd_exec, unknown, lfi)
15  0.028571            (unknown, xss, lfi)
16  0.028571  (cmd_exec, unknown, xss, lfi)
17  0.057143          (wp-content, unknown)
18  0.057143         (wp-content, cmd_exec)
19  0.057143              (wp-content, xss)

In [22]:
import psycopg2

conn = psycopg2.connect(database="web_honeypot_generated", user = "postgres", password = "admin", host = "127.0.0.1", port = "5432")

print("Opened database successfully")

Opened database successfully

In [23]:
# create table
cur = conn.cursor()
cur.execute('''CREATE TABLE assoc_rules_attack_types (
            ID INT PRIMARY KEY     NOT NULL,
            SUPPORT           REAL    NOT NULL,
            ATTACK_TYPE            VARCHAR(255)     NOT NULL);''')

print("Table created successfully")

conn.commit()

Table created successfully

In [24]:
# insert data

cur = conn.cursor()

insert_query = """
    INSERT INTO assoc_rules_attack_types (ID, SUPPORT, ATTACK_TYPE)
    VALUES (%s, %s, %s)
"""

for idx, row in frequent_itemsets.iterrows():
    cur.execute(
        insert_query,
        (int(idx), float(row["support"]), str(list(row["itemsets"])))
    )

conn.commit()
print("Records created successfully")
conn.close()

Records created successfully