In [1]:
import pandas as pd

df = pd.read_csv("../detected.csv")

df.head(5)

,timestamp,method,path,status,ip,port,uuid,sess_uuid,detection_name,detection_type,user_agent,referer,attack_name,attack_type
0,2025-05-22T07:53:51.660458,GET,/,200,172.18.0.1,38158,5da851cd-09cc-4bb7-a200-f07dad1a8897,e906dd52-8d43-4894-98e0-3b6b93073434,index,1,curl/7.81.0,NaN,Unknown,0
1,2025-05-22T07:54:41.725206,GET,/,200,172.18.0.1,51798,5da851cd-09cc-4bb7-a200-f07dad1a8897,4071c0d0-c143-4171-9d72-57001462d87e,index,1,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,NaN,Unknown,0
2,2025-05-22T07:54:41.929057,GET,/stylesheets/jquery/jquery-ui-1.11.0.css?15286...,200,172.18.0.1,51806,5da851cd-09cc-4bb7-a200-f07dad1a8897,c959aef7-3a6f-4f11-8898-6c8402172368,index,1,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,http://localhost/,Unknown,0
3,2025-05-22T07:54:42.114829,GET,/stylesheets/application.css?1528612569,200,172.18.0.1,51812,5da851cd-09cc-4bb7-a200-f07dad1a8897,c959aef7-3a6f-4f11-8898-6c8402172368,index,1,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,http://localhost/,Unknown,0
4,2025-05-22T07:54:42.131187,GET,/stylesheets/responsive.css?1528612569,200,172.18.0.1,51826,5da851cd-09cc-4bb7-a200-f07dad1a8897,c959aef7-3a6f-4f11-8898-6c8402172368,index,1,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,http://localhost/,Unknown,0

In [2]:
sess_uuids = df["sess_uuid"]

sess_uuids_matrix = []
tmp = []

for i, x in enumerate(sess_uuids):
  if i % 10 == 0 and i != 0:
    sess_uuids_matrix.append(tmp)
    tmp = []
  tmp.append(x)

# Add the last group if not empty
if tmp:
  sess_uuids_matrix.append(tmp)

sess_uuids_matrix

[['e906dd52-8d43-4894-98e0-3b6b93073434',
  '4071c0d0-c143-4171-9d72-57001462d87e',
  'c959aef7-3a6f-4f11-8898-6c8402172368',
  'c959aef7-3a6f-4f11-8898-6c8402172368',
  'c959aef7-3a6f-4f11-8898-6c8402172368',
  'c959aef7-3a6f-4f11-8898-6c8402172368',
  'c959aef7-3a6f-4f11-8898-6c8402172368',
  'c959aef7-3a6f-4f11-8898-6c8402172368',
  'c959aef7-3a6f-4f11-8898-6c8402172368',
  'c959aef7-3a6f-4f11-8898-6c8402172368'],
 ['cf9608bd-8c87-4ac4-952d-fd0ddd41e5e3',
  'cf9608bd-8c87-4ac4-952d-fd0ddd41e5e3',
  'cf9608bd-8c87-4ac4-952d-fd0ddd41e5e3',
  'cf9608bd-8c87-4ac4-952d-fd0ddd41e5e3',
  'cf9608bd-8c87-4ac4-952d-fd0ddd41e5e3',
  'cf9608bd-8c87-4ac4-952d-fd0ddd41e5e3',
  'cf9608bd-8c87-4ac4-952d-fd0ddd41e5e3',
  'cf9608bd-8c87-4ac4-952d-fd0ddd41e5e3',
  'cf9608bd-8c87-4ac4-952d-fd0ddd41e5e3',
  'b1de7b3f-b717-414e-a39a-40df849b60d9'],
 ['b1de7b3f-b717-414e-a39a-40df849b60d9',
  'b1de7b3f-b717-414e-a39a-40df849b60d9',
  'b1de7b3f-b717-414e-a39a-40df849b60d9',
  'b1de7b3f-b717-414e-a39a-40df849b60d9',
  'b1de7b3f-b717-414e-a39a-40df849b60d9',
  'b1de7b3f-b717-414e-a39a-40df849b60d9',
  'b1de7b3f-b717-414e-a39a-40df849b60d9',
  '68ddfc8c-970b-400e-b69f-8117ed501b1b',
  '68ddfc8c-970b-400e-b69f-8117ed501b1b',
  '68ddfc8c-970b-400e-b69f-8117ed501b1b'],
 ['68ddfc8c-970b-400e-b69f-8117ed501b1b',
  '68ddfc8c-970b-400e-b69f-8117ed501b1b',
  '68ddfc8c-970b-400e-b69f-8117ed501b1b',
  '68ddfc8c-970b-400e-b69f-8117ed501b1b',
  '20b9b294-c5a2-4ca0-872a-e6bd688e5ec7',
  '00bd7699-0b44-408a-87b4-feeff8cec178',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f'],
 ['dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'dc2041af-b423-464e-96f7-1513ac86003f',
  'd668089c-67d6-4b94-94c9-8c85f55a0eff',
  '8f0c760b-97e0-47a6-aa46-0be70abda3b9',
  '71f5677c-8c1b-4b9f-92c6-f6b603200928',
  'caf462bb-1dcc-4d63-9411-ebf3c306212a'],
 ['9a86cdc4-a292-4923-8268-40fb3de39665',
  'e08f5a07-0fa5-431a-827f-8792e4f8da9f',
  '6ced592a-1094-4938-b85f-50eee4e87e41',
  '6e0e5c0f-20be-4266-b33f-7fb006228b8c',
  '188a18eb-fbb3-4dcc-8154-9eeb4dad828d',
  '463e2c30-3093-435c-8c32-52b1d4121719',
  'cc3b407a-9183-4d8a-98fa-2264587a01e9',
  '487dbe42-9cd8-4fec-a075-feec404c7f5d',
  '71aa70de-7005-4316-aacb-81df4b4a9012',
  '27c42c1b-314d-4dea-9d7e-a4ee8c359475'],
 ['79bdb2e3-1532-45fd-91f4-b19e04fc2b64',
  'aa177d5c-c6d8-46ff-9b9a-f05cca67cc0f',
  '1336f7e5-d845-42ea-a792-ae5f8585c1d3',
  '261eefac-aa0b-4439-b7ac-bec5b8e74982',
  '1d43063c-b616-4820-9a26-2eab347963a1',
  '48e8686f-ce92-4b9d-b5b3-d4fdb690c248',
  '7b03618b-bcd4-4366-adca-8ac015ea4048',
  '812a0c73-b196-4c20-a451-fdf2daa15669',
  '26b56dad-db5b-4765-979c-118480a22c3d',
  'c75f9ba7-4f47-4e72-aabc-60f0a1ee176b'],
 ['c64cecc3-96bb-4eb8-a998-c8524102979c',
  'e3023545-f323-42e2-b061-b9312b9db282',
  '8e721069-379b-4203-abde-f31026ef71e0',
  '80b52a2f-8fab-4ef4-97e7-f38624831ef9',
  '3856d96a-ee09-4bec-be6c-befefc6d146c',
  '605914ea-8943-4d50-8992-cd1729acaba6',
  '16b63c51-2fc3-4f23-a4d3-98483b01a9dd',
  '1e07fd27-08b0-4149-84f1-35da71fe0680',
  '07cabfdf-99df-4a1b-9849-f7807c69a529',
  'fd29d7cd-f07a-40f6-8cbf-ac67bad5d1f6'],
 ['d251648c-007b-4972-aa56-c3517dc8b40c',
  'a00d952f-adcb-46bb-afde-326a685cd431',
  'a8173d22-f1a4-47e1-924f-15aafdbdbfac',
  '61bb874c-8edf-4e34-9023-4b719361fca3',
  '0e6c9845-5794-4915-8858-ab7a83f7c562',
  '12b56343-f1aa-4e4a-aa7c-08e2df6e1c55',
  '3cdb8706-e4f1-4f45-a7f8-b9c5accefe82',
  'd6ec2a69-6f59-40a3-90ac-8fb2ea1a090a',
  '15133f0f-8a67-4937-92d8-d20b2c28a5e7',
  '6eecf1cf-65db-4c4c-baeb-5e84e1a28248'],
 ['c27ad568-0473-4a4c-8b7e-2a8c1c3bf652',
  '4ece736c-c09d-4e3f-b87c-472a8d7ef90c',
  '0899238f-8724-4100-83f9-1511c53d4acd',
  '4650960d-a480-45ac-935d-09aafae36754',
  '9a52a523-f8c9-44e3-8193-9f5f5b65f595',
  'b85e8e24-5d08-4e62-8ef5-0f0a1c93a6ac',
  '4416fea9-5e79-4cfb-9318-877b635d1f87',
  '0daf322d-b0dd-4018-a376-4673ca32737c',
  '5cb1c744-9eff-4829-9568-968724235038',
  '892221ca-644b-439e-9054-e939df8d80d4'],
 ['41b81c52-1cea-49e9-a30f-721eb3935d42',
  '26a655e2-54ce-48c3-bd58-0d839514ab5f',
  '065802eb-d726-4ff8-add8-3fb5336b87b6',
  '5b0f0769-ace6-4594-85e2-1d4ff5860a2f',
  'cfb78a84-e38a-46b2-8895-953771e77bfe',
  '9d0decaa-7de5-467c-a1d6-207b42ae9d61',
  'facb0d3b-e116-4162-b97f-03f672f2f707',
  '505fe7ee-063b-4c94-accd-4f449ae12059',
  '41e21cd3-0efa-46af-9f5a-7729fa49f745',
  '4ab8576c-7252-4295-913b-2db8a8a57996'],
 ['255ca46a-eb17-4edc-8656-7e810227e908',
  '03c710c2-3595-437b-a10e-f66007f09670',
  '57addf23-37c5-4b0f-a2d5-2cd63ad19ce7',
  'fe031630-69dc-465e-9331-55eb1187e709',
  '643a5de7-0b56-4c50-9fa9-90fff69483de',
  '098fc9cf-957a-47dc-9649-19af1eab6460',
  'fcecf921-5ab2-4336-a289-f284366203f3',
  '7237790d-cffc-434d-8932-1b1aecc1cb55',
  'f11f2d18-5744-4524-ac69-6d2e6c7e6a28',
  '294b4819-0549-4327-8653-ba4b85f4d326'],
 ['38d6ebf0-6190-408a-86d9-9f9f4ebcadd3',
  '3dd64636-d058-436d-ae7f-460ce0907f97',
  '02cc24f6-ff46-4026-8633-8dbc94b441f0',
  'db3ad219-9e31-43c1-a770-0f2676db3d67',
  '5edff685-f6b6-460c-a475-013e9de26a84',
  'd7b575f7-5ae4-48eb-8bf7-66ecf02aaa72',
  '8acf93ee-62b7-49b4-89de-957553cf6516',
  '2d862ff0-8d4e-4c2f-969d-d9a8ba0aed4d',
  '809eaaa1-4674-4b70-991c-73dfadd917be',
  'ab53a071-c1f4-4da4-b04d-ab3f30a39c63'],
 ['5df0b41d-170e-461b-acc6-ecaaaad33b7f',
  '40814ef2-6993-458b-8ebb-647be1fca64e',
  'ed2a596f-3fb3-4542-80ff-18864036d3d2',
  '518cc9d2-1cf3-458b-83a6-afd99496e79a',
  'ed777645-c7fe-438a-9ca5-3e3fbbd05676',
  '061d3516-9fcd-4ee1-8377-8d0946f8ff6b',
  'a515cb5f-df6d-4913-959b-431808a1e98c',
  '9098f685-1e54-4a40-a5ae-1322211e3e39',
  'dc8b9ce9-cbae-4f43-bb45-89ea51a624f6',
  'a545e875-e7c0-44f9-8686-1a6fdfeda303'],
 ['f99634ba-27ae-4d93-a470-1a8858fbbc65',
  'b1664acc-689e-4362-9960-57ec802d5c87',
  '09d34be7-5215-4a6a-ab9e-6db9fa3ebf17',
  'e5bae0c2-8f04-4be7-8c4b-05ad38037c1c',
  '41ecb414-28b4-470d-bdd9-c343ecbf2444',
  '396f92f2-57ba-4101-b086-ccd499a98e13',
  '25d1a677-b042-4708-abf5-d67c07978861',
  'a53bd15e-4206-491f-bb8e-6eb842c75637',
  '540ba2f1-b9d8-4422-b678-8376082f411f',
  '4c4179cf-cc4d-4075-9843-a093b412e65e'],
 ['2ff8bbd2-a118-4743-be3e-ceda1c166e10',
  '07d72b11-3fb4-4b39-a0ea-0ef29a4df14e',
  'bf512cbe-f81a-4f8f-b645-b7bd70b205ff',
  '962a3683-8bfd-4515-97a1-cd7f1ad5373f',
  '3b5ae953-8256-4cbb-b232-ddb330b1d1e0',
  '96b7ae9b-7f98-42b5-a4aa-132def8c3c62',
  'cd121f0d-f9a3-4313-bf4c-d69c3dac8ce2',
  'deffeee1-75fb-4184-ab4c-bbe88c539ed7',
  '31d2b063-06dd-480f-a37e-094ef7661544',
  '9a81e62e-ecbc-452e-8e07-95a378f28825'],
 ['bf7a4b6c-c832-4b9e-87cf-59c8f82645fc',
  '9ef24364-ffb5-48a0-bcd6-ab890e41b53c',
  '386583e4-dd32-495e-92cb-7d2d4057d153',
  'a0cd6399-015f-4e45-b128-a9bc452f7ce5',
  '92ec9960-3e68-4904-bd87-a0c4238ebe73',
  'b3a620ff-3cae-4d73-8df1-c559231771a0',
  '928d77fd-fe63-451a-9427-954dadfa139d',
  '2da2bb65-ff62-421a-9cae-d5c7e803adf3',
  '4e5ea1c8-9d3f-4176-a975-e2b05b87d6b8',
  'e32958da-ad4b-4b55-a729-4daab30b3e00'],
 ['0deb9738-92dd-4385-8bbe-1acaee252ff8',
  '25702676-6f94-47a3-906d-5f2c1b5978be',
  '7cdb482c-9077-4367-bd0c-a1415a7cb76d',
  '321fb3da-3d38-4e4f-83b6-2e5e6ee7c384',
  '7454b333-0269-4cda-8a0d-1aac77efd122',
  'ef729a28-800a-436f-b29a-ca6fe8e6cd40',
  '7e2790f2-34d6-4024-b344-d996e35bf474',
  '75632632-c511-491e-a57c-7a9f81a784e1',
  '8045cd0f-1b26-4699-8272-6287a64fbbd7',
  'cc76f6bb-8740-4d90-927f-c0c54635b486'],
 ['1bf2f76c-228f-4f67-987f-8af8c5afeb9f',
  'dd00b121-7de4-46e0-af93-8ad4b3dbd32e',
  'c7b85e1f-3211-47f8-81a3-c846c6656f04',
  'e02b0b9a-b060-4885-b5d5-cf76356381b0',
  '2179d8d4-d5a7-4278-935d-483dd4b92bf1',

In [3]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, fpmax, fpgrowth

te = TransactionEncoder()
te_ary = te.fit(sess_uuids_matrix).transform(sess_uuids_matrix)
df = pd.DataFrame(te_ary, columns=te.columns_)

df

,0007dace-0667-465a-b6fd-4b579c9b14de,0009f88f-d0ea-4818-96c3-4478842656dd,00122eba-19dc-4369-aa56-175718b4c9cb,0019794f-2c31-4f11-b62f-7eae6d4a6915,00204bd5-f1d9-4fbc-9d63-596df133c68b,002aec4b-a476-4c85-bb32-bf1891a87d1a,002dbfbf-67cc-4629-a97c-ba1a7cabb204,0031e0d8-9931-4667-a50f-815afb2f39ac,00396a4e-6395-4b0d-9c9c-738ea12a1f2c,00417277-6ad6-4937-8f8f-529be9d5a6e3,...,ffcd59e0-33a3-4cda-b47e-f920a8c477ff,ffce1225-49e1-4c7f-9ed4-ed9f1a2ced6f,ffd0024d-78dd-4521-9f6c-47faf150cf50,ffdbb5f1-c330-418b-9dc6-3df16f1be9a7,ffdc229a-4e73-4c08-af51-3b63fa36aa90,ffdf3c81-9af6-4c0b-b195-2414156d71f2,ffe8a3e8-045a-419c-b8e6-afd0b07c6a66,ffeb162b-f2ce-4025-89fd-bcae1417ee54,fffaea1e-9d4a-4110-b5dd-282228d871a2,fffcc425-de35-4c05-a379-a3f977c0977b
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4926,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4927,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4928,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4929,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4930,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [4]:
# frequent_itemsets = fpgrowth(df, min_support=0.3, use_colnames=True)
frequent_itemsets = fpgrowth(df, min_support=0.1, use_colnames=True)
### alternatively:
#frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
#frequent_itemsets = fpmax(df, min_support=0.6, use_colnames=True)

frequent_itemsets.head(20)

     support                                           itemsets
0   0.314541             (565fdd14-b7b0-4342-bf7e-06e1fb661b5d)
1   0.301562             (9d38eec3-4842-433e-b874-c5d687f5a32e)
2   0.294666             (33298e06-ce8a-4fcd-ac17-d84c1bd845f3)
3   0.238288             (78cddcdc-b760-4b6c-b160-d0eb0a3218b6)
4   0.276415             (63fffe44-f301-4f67-90cd-04f3afc89588)
5   0.116204             (cf3e7c2f-3f51-4edb-9d4a-ca7133d937de)
6   0.195295             (bc16ac42-86e7-4e12-97ad-d91e7324b98d)
7   0.163861             (0363acfd-e0ef-49b4-b273-d3a4ce8ea451)
8   0.141148             (07a7a196-a2f2-4b7a-a0fd-25664309d01a)
9   0.142162             (675e0a67-d778-4050-bbbc-554ba5caf72a)
10  0.118637             (c28e0c4f-44d5-4509-b012-519aa7a22da1)
11  0.122896             (5e0f6965-f41d-49e1-b9f3-4c865d64c36d)
12  0.252890  (9d38eec3-4842-433e-b874-c5d687f5a32e, 565fdd1...
13  0.261610  (9d38eec3-4842-433e-b874-c5d687f5a32e, 33298e0...
14  0.246603  (33298e06-ce8a-4fcd-ac17-d84c1bd845f3, 565fdd1...
15  0.215372  (9d38eec3-4842-433e-b874-c5d687f5a32e, 33298e0...
16  0.208477  (9d38eec3-4842-433e-b874-c5d687f5a32e, 78cddcd...
17  0.205841  (78cddcdc-b760-4b6c-b160-d0eb0a3218b6, 33298e0...
18  0.201582  (78cddcdc-b760-4b6c-b160-d0eb0a3218b6, 565fdd1...
19  0.166092  (63fffe44-f301-4f67-90cd-04f3afc89588, 78cddcd...

In [9]:
import psycopg2

conn = psycopg2.connect(database="web_honeypot_generated", user = "postgres", password = "admin", host = "127.0.0.1", port = "5432")

print("Opened database successfully")

Opened database successfully

In [6]:
# create table
cur = conn.cursor()
cur.execute('''CREATE TABLE assoc_rules_sess_uuid (
            ID INT PRIMARY KEY     NOT NULL,
            SUPPORT           REAL    NOT NULL,
            SESS_UUID            VARCHAR(255)     NOT NULL);''')

print("Table created successfully")

conn.commit()

Table created successfully

In [10]:
# insert data

cur = conn.cursor()

insert_query = """
    INSERT INTO assoc_rules_sess_uuid (ID, SUPPORT, SESS_UUID)
    VALUES (%s, %s, %s)
"""

for idx, row in frequent_itemsets.iterrows():
    cur.execute(
        insert_query,
        (int(idx), float(row["support"]), str(list(row["itemsets"])))
    )

conn.commit()
print("Records created successfully")
conn.close()

Records created successfully