In [1]:
import pandas as pd

df = pd.read_csv("../detected.csv")

df.head(5)

,timestamp,method,path,status,ip,port,uuid,sess_uuid,detection_name,detection_type,user_agent,referer,attack_name,attack_type
0,2025-05-22T07:53:51.660458,GET,/,200,172.18.0.1,38158,5da851cd-09cc-4bb7-a200-f07dad1a8897,e906dd52-8d43-4894-98e0-3b6b93073434,index,1,curl/7.81.0,NaN,Unknown,0
1,2025-05-22T07:54:41.725206,GET,/,200,172.18.0.1,51798,5da851cd-09cc-4bb7-a200-f07dad1a8897,4071c0d0-c143-4171-9d72-57001462d87e,index,1,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,NaN,Unknown,0
2,2025-05-22T07:54:41.929057,GET,/stylesheets/jquery/jquery-ui-1.11.0.css?15286...,200,172.18.0.1,51806,5da851cd-09cc-4bb7-a200-f07dad1a8897,c959aef7-3a6f-4f11-8898-6c8402172368,index,1,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,http://localhost/,Unknown,0
3,2025-05-22T07:54:42.114829,GET,/stylesheets/application.css?1528612569,200,172.18.0.1,51812,5da851cd-09cc-4bb7-a200-f07dad1a8897,c959aef7-3a6f-4f11-8898-6c8402172368,index,1,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,http://localhost/,Unknown,0
4,2025-05-22T07:54:42.131187,GET,/stylesheets/responsive.css?1528612569,200,172.18.0.1,51826,5da851cd-09cc-4bb7-a200-f07dad1a8897,c959aef7-3a6f-4f11-8898-6c8402172368,index,1,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,http://localhost/,Unknown,0

In [7]:
user_agents = df["user_agent"]

user_agents_matrix = []
tmp = []

for i, x in enumerate(user_agents):
  if i % 10 == 0 and i != 0:
    user_agents_matrix.append(tmp)
    tmp = []
  tmp.append(x)

# Add the last group if not empty
if tmp:
  user_agents_matrix.append(tmp)

user_agents_matrix

[['curl/7.81.0',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36'],
 ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36'],
 ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36'],
 ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  'sqlmap/1.6.4#stable (https://sqlmap.org)',
  '8814',
  'sqlmap/1.6.4#stable (https://sqlmap.org).(".,),(\'.',
  'sqlmap/1.6.4#stable (https://sqlmap.org)\'ipfNiR<\'">jJqJPT',
  'sqlmap/1.6.4#stable (https://sqlmap.org)) AND 2022=3304-- Rnsw'],
 ["sqlmap/1.6.4#stable (https://sqlmap.org)') AND 8087=7123-- mhQn",
  "sqlmap/1.6.4#stable (https://sqlmap.org)' AND 5323=6138-- kscR",
  'sqlmap/1.6.4#stable (https://sqlmap.org)" AND 6310=5148-- BDxg',
  'sqlmap/1.6.4#stable (https://sqlmap.org)) AND 1513=4169 AND (5197=5197',
  'sqlmap/1.6.4#stable (https://sqlmap.org))) AND 9191=9877 AND ((2859=2859',
  'sqlmap/1.6.4#stable (https://sqlmap.org)))) AND 4773=5618 AND (((7513=7513',
  'sqlmap/1.6.4#stable (https://sqlmap.org) AND 9726=3962',
  "sqlmap/1.6.4#stable (https://sqlmap.org)') AND 3739=8261 AND ('TODV'='TODV",
  "sqlmap/1.6.4#stable (https://sqlmap.org)')) AND 1890=5408 AND (('VmpC'='VmpC",
  "sqlmap/1.6.4#stable (https://sqlmap.org)'))) AND 1012=3605 AND ((('zQeZ'='zQeZ"],
 ["sqlmap/1.6.4#stable (https://sqlmap.org)' AND 5835=6633 AND 'AzcO'='AzcO",
  "sqlmap/1.6.4#stable (https://sqlmap.org)') AND 7333=4392 AND ('IMyu' LIKE 'IMyu",
  "sqlmap/1.6.4#stable (https://sqlmap.org)')) AND 7006=7982 AND (('dyxe' LIKE 'dyxe",
  "sqlmap/1.6.4#stable (https://sqlmap.org)'))) AND 4243=7422 AND ((('Ltjn' LIKE 'Ltjn",
  "sqlmap/1.6.4#stable (https://sqlmap.org)%' AND 5623=7266 AND 'fQkz%'='fQkz",
  "sqlmap/1.6.4#stable (https://sqlmap.org)' AND 9491=1315 AND 'Ovpc' LIKE 'Ovpc",
  'sqlmap/1.6.4#stable (https://sqlmap.org)") AND 6776=9006 AND ("pBnS"="pBnS',
  'sqlmap/1.6.4#stable (https://sqlmap.org)")) AND 7830=8949 AND (("EvCY"="EvCY',
  'sqlmap/1.6.4#stable (https://sqlmap.org)"))) AND 3276=1881 AND ((("bghT"="bghT',
  'sqlmap/1.6.4#stable (https://sqlmap.org)" AND 4663=3535 AND "QoUU"="QoUU'],
 ['sqlmap/1.6.4#stable (https://sqlmap.org)") AND 1691=1555 AND ("WjwT" LIKE "WjwT',
  'sqlmap/1.6.4#stable (https://sqlmap.org)")) AND 6194=1258 AND (("rTLt" LIKE "rTLt',
  'sqlmap/1.6.4#stable (https://sqlmap.org)"))) AND 5279=6557 AND ((("LFeN" LIKE "LFeN',
  'sqlmap/1.6.4#stable (https://sqlmap.org)" AND 7112=6172 AND "wQrQ" LIKE "wQrQ',
  'sqlmap/1.6.4#stable (https://sqlmap.org) AND 9286=3688-- jKix',

In [8]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, fpmax, fpgrowth

te = TransactionEncoder()
te_ary = te.fit(user_agents_matrix).transform(user_agents_matrix)
df = pd.DataFrame(te_ary, columns=te.columns_)

df

,(2507=4436)*0x73716c6d61702f312e362e3423737461626c65202868747470733a2f2f73716c6d61702e6f726729,(3911=6966)*6966,(4408=4408 AND SLEEP(5)),(CASE WHEN (2518=6902) THEN 2518 ELSE 2518*(SELECT 2518 FROM DUAL UNION SELECT 6902 FROM DUAL) END),(CASE WHEN (4166=4166) THEN SLEEP(5) ELSE 4166 END),(CASE WHEN (7435=5336) THEN 'sqlmap/1.6.4#stable (https://sqlmap.org)' ELSE 7435*(SELECT 7435 FROM DUAL UNION SELECT 5336 FROM DUAL) END),(CASE WHEN 3661=8674 THEN 'sqlmap/1.6.4#stable (https://sqlmap.org)' ELSE NULL END),(CASE WHEN 3893=8767 THEN 3893 ELSE NULL END),(CAST((CHR(113)||CHR(98)||CHR(112)||CHR(120)||CHR(113))||(SELECT (CASE WHEN (5674=5674) THEN 1 ELSE 0 END))::text||(CHR(113)||CHR(122)||CHR(120)||CHR(98)||CHR(113)) AS NUMERIC)),"(CAST((CHR(113)||CHR(98)||CHR(112)||CHR(120)||CHR(113))||(SELECT 1 FROM GENERATE_SERIES(1880,1880,CASE WHEN (1880=1880) THEN 1 ELSE 0 END) LIMIT 1)::text||(CHR(113)||CHR(122)||CHR(120)||CHR(98)||CHR(113)) AS NUMERIC))",...,"sqlmap/1.6.4#stable (https://sqlmap.org)||(SELECT CHR(69)||CHR(75)||CHR(90)||CHR(83) FROM DUAL WHERE 7805=7805 AND 3773=DBMS_PIPE.RECEIVE_MESSAGE(CHR(114)||CHR(114)||CHR(66)||CHR(84),5)--",sqlmap/1.6.4#stable (https://sqlmap.org)||(SELECT CHR(78)||CHR(81)||CHR(75)||CHR(74) FROM DUAL WHERE 4933=4933 AND 4610=UTL_INADDR.GET_HOST_ADDRESS(CHR(113)||CHR(98)||CHR(112)||CHR(120)||CHR(113)||(SELECT (CASE WHEN (4610=4610) THEN 1 ELSE 0 END) FROM DUAL)||CHR(113)||CHR(122)||CHR(120)||CHR(98)||CHR(113)))||,sqlmap/1.6.4#stable (https://sqlmap.org)||(SELECT CHR(85)||CHR(73)||CHR(78)||CHR(75) WHERE 1934=1934 AND 4610=UTL_INADDR.GET_HOST_ADDRESS(CHR(113)||CHR(98)||CHR(112)||CHR(120)||CHR(113)||(SELECT (CASE WHEN (4610=4610) THEN 1 ELSE 0 END) FROM DUAL)||CHR(113)||CHR(122)||CHR(120)||CHR(98)||CHR(113)))||,"sqlmap/1.6.4#stable (https://sqlmap.org)||(SELECT CHR(86)||CHR(107)||CHR(75)||CHR(88) WHERE 3753=3753 AND 3578=CTXSYS.DRITHSX.SN(3578,(CHR(113)||CHR(98)||CHR(112)||CHR(120)||CHR(113)||(SELECT (CASE WHEN (3578=3578) THEN 1 ELSE 0 END) FROM DUAL)||CHR(113)||CHR(122)||CHR(120)||CHR(98)||CHR(113))))||","sqlmap/1.6.4#stable (https://sqlmap.org)||(SELECT CHR(87)||CHR(68)||CHR(118)||CHR(118) FROM DUAL WHERE 8605=8605 AND 8913=DBMS_PIPE.RECEIVE_MESSAGE(CHR(65)||CHR(101)||CHR(80)||CHR(77),5))||",sqlmap/1.6.4#stable (https://sqlmap.org)||(SELECT CHR(99)||CHR(104)||CHR(112)||CHR(109) WHERE 4965=4965 AND 6808=DBMS_UTILITY.SQLID_TO_SQLHASH((CHR(113)||CHR(98)||CHR(112)||CHR(120)||CHR(113)||(SELECT (CASE WHEN (6808=6808) THEN 1 ELSE 0 END) FROM DUAL)||CHR(113)||CHR(122)||CHR(120)||CHR(98)||CHR(113))))||,sqlmap/1.6.4#stable (https://sqlmap.org)||(SELECT XHFB FROM DUAL WHERE 6095=6095 AND 6928=6888)||,sqlmap/1.6.4#stable (https://sqlmap.org)||(SELECT bNFc WHERE 6507=6507 AND 7841=5376)||,sqlmap/1.6.4#stable (https://sqlmap.org)||(SELECT cAUz WHERE 7179=7179 AND 2874=(SELECT (CASE WHEN (2874=6349) THEN 2874 ELSE (SELECT 6349 UNION SELECT 4881) END))-- tUEX,sqlmap/1.6.4#stable (https://sqlmap.org)||(SELECT xKHW FROM DUAL WHERE 5872=5872 AND 6383=(SELECT (CASE WHEN (6383=7784) THEN 6383 ELSE (SELECT 7784 UNION SELECT 6679) END))-- kggb
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4926,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4927,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4928,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4929,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4930,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [16]:
# frequent_itemsets = fpgrowth(df, min_support=0.3, use_colnames=True)
frequent_itemsets = fpgrowth(df, min_support=0.001, use_colnames=True)
### alternatively:
#frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
#frequent_itemsets = fpmax(df, min_support=0.6, use_colnames=True)

frequent_itemsets.head(11)

     support                                           itemsets
0   0.001217                                      (curl/7.81.0)
1   0.141351         (sqlmap/1.6.4#stable (https://sqlmap.org))
2   0.007098  (Mozilla/5.00 (Nikto/2.1.5) (Evasions:None) (T...
3   0.001825  (Mozilla/5.00 (Nikto/2.1.5) (Evasions:None) (T...
4   0.001420  (Mozilla/5.00 (Nikto/2.1.5) (Evasions:None) (T...
5   0.001420  (Mozilla/5.00 (Nikto/2.1.5) (Evasions:None) (T...
6   0.001014  (Mozilla/5.00 (Nikto/2.1.5) (Evasions:None) (T...
7   0.679984  (Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...
8   0.006490  (Mozilla/4.0 (compatible; MSIE 8.0; Windows NT...
9   0.006490  (Mozilla/4.0 (compatible; MSIE 7.0; Windows NT...
10  0.007504  (Mozilla/4.0 (compatible; MSIE 6.0; Windows NT...