In [1]:
import pandas as pd

df = pd.read_csv("../detected.csv")

df.head(5)

,timestamp,method,path,status,ip,port,uuid,sess_uuid,detection_name,detection_type,user_agent,referer,attack_name,attack_type
0,2025-05-22T07:53:51.660458,GET,/,200,172.18.0.1,38158,5da851cd-09cc-4bb7-a200-f07dad1a8897,e906dd52-8d43-4894-98e0-3b6b93073434,index,1,curl/7.81.0,NaN,Unknown,0
1,2025-05-22T07:54:41.725206,GET,/,200,172.18.0.1,51798,5da851cd-09cc-4bb7-a200-f07dad1a8897,4071c0d0-c143-4171-9d72-57001462d87e,index,1,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,NaN,Unknown,0
2,2025-05-22T07:54:41.929057,GET,/stylesheets/jquery/jquery-ui-1.11.0.css?15286...,200,172.18.0.1,51806,5da851cd-09cc-4bb7-a200-f07dad1a8897,c959aef7-3a6f-4f11-8898-6c8402172368,index,1,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,http://localhost/,Unknown,0
3,2025-05-22T07:54:42.114829,GET,/stylesheets/application.css?1528612569,200,172.18.0.1,51812,5da851cd-09cc-4bb7-a200-f07dad1a8897,c959aef7-3a6f-4f11-8898-6c8402172368,index,1,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,http://localhost/,Unknown,0
4,2025-05-22T07:54:42.131187,GET,/stylesheets/responsive.css?1528612569,200,172.18.0.1,51826,5da851cd-09cc-4bb7-a200-f07dad1a8897,c959aef7-3a6f-4f11-8898-6c8402172368,index,1,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,http://localhost/,Unknown,0

In [2]:
port = df["port"]

ports_matrix = []
tmp = []

for i, x in enumerate(port):
  if i % 10 == 0 and i != 0:
    ports_matrix.append(tmp)
    tmp = []
  tmp.append(x)

# Add the last group if not empty
if tmp:
  ports_matrix.append(tmp)

ports_matrix

[[38158, 51798, 51806, 51812, 51826, 51842, 51844, 51848, 51854, 38510],
 [38518, 38534, 38550, 38552, 38562, 38574, 38590, 38594, 38602, 38616],
 [38628, 38640, 38658, 38654, 38660, 38674, 38686, 38700, 38704, 38706],
 [38720, 38732, 38740, 38742, 41188, 41204, 60570, 60578, 60586, 60594],
 [60606, 60612, 60628, 60620, 60646, 60644, 60652, 60662, 60672, 60682],
 [60692, 60706, 60726, 60720, 60736, 60752, 60768, 60770, 60784, 60798],
 [60800, 60816, 60820, 60844, 60836, 60846, 60856, 60870, 60878, 60894],
 [60898, 60906, 60908, 60918, 60922, 60938, 60944, 60956, 60982, 60966],
 [60984, 32768, 32784, 32792, 32798, 32824, 32812, 32828, 32836, 32848],
 [32858, 32872, 32888, 32874, 32894, 32900, 32910, 32918, 32932, 32920],
 [32938, 32950, 32960, 32968, 32970, 32986, 32978, 32998, 33026, 33010],
 [33036, 33042, 33052, 33058, 33070, 33074, 33076, 33100, 33092, 33108],
 [33114, 33124, 33126, 33128, 33142, 33158, 33178, 33164, 33184, 33196],
 [33198, 33200, 33212, 33224, 33216, 33226, 33240, 33248, 33252, 33268],
 [33278, 33282, 33292, 33302, 33308, 33326, 33314, 33342, 33350, 33366],
 [33374, 33388, 33402, 33420, 33416, 33430, 33442, 33446, 33458, 33480],
 [33466, 33494, 33506, 33512, 33516, 33522, 33534, 33546, 33562, 33570],
 [33576, 33592, 33598, 33606, 33620, 33634, 33650, 33652, 33660, 33664],
 [33682, 33666, 33698, 33700, 33716, 33722, 33732, 33758, 33744, 33760],
 [33768, 33770, 33786, 33790, 33806, 33812, 33836, 33828, 33844, 33854],
 [33870, 33882, 33894, 33912, 33900, 33924, 33930, 33936, 33950, 33962],
 [33968, 33978, 33988, 33996, 34012, 34022, 34032, 34046, 34052, 34068],
 [34058, 34074, 34076, 34088, 34090, 34106, 34118, 34108, 34120, 34122],
 [34126, 34128, 34152, 34138, 34156, 34164, 34174, 34184, 34192, 34204],
 [34222, 34208, 34234, 34250, 34256, 34264, 34274, 34304, 34288, 34320],
 [34322, 34338, 34348, 34358, 34366, 34388, 34378, 34394, 34406, 34416],
 [34428, 34442, 34444, 34452, 34460, 34474, 34490, 34506, 34518, 34532],
 [34546, 34560, 34574, 34578, 34586, 34598, 34626, 34610, 34638, 34648],
 [34664, 34668, 34682, 34690, 34702, 34712, 34728, 34750, 34740, 34760],
 [34762, 34778, 34786, 34788, 34802, 34812, 34820, 34814, 34832, 34846],
 [34862, 34876, 34890, 34888, 34902, 34908, 34922, 34924, 34942, 34936],
 [34946, 34952, 34954, 34958, 34972, 34984, 34980, 35000, 35004, 35010],
 [35012, 35016, 35022, 35018, 35026, 35040, 35044, 35056, 35060, 35066],
 [35086, 35074, 35088, 35090, 35098, 35100, 35106, 35110, 35126, 35128],
 [35130, 35144, 35150, 35156, 35162, 35178, 35188, 35190, 35208, 35196],
 [35238, 35224, 35254, 35260, 35262, 35272, 35268, 35280, 35300, 35290],
 [35312, 35310, 35320, 35328, 35340, 35354, 35366, 35372, 35378, 35384],
 [35382, 35390, 35400, 35394, 35424, 35414, 35434, 35430, 35456, 35450],
 [35480, 35468, 35500, 35488, 35522, 35512, 35528, 35540, 35552, 35554],
 [35580, 35568, 35602, 35594, 35620, 35604, 35638, 35636, 35660, 35646],
 [35686, 35674, 35696, 35690, 35718, 35702, 35734, 35732, 35750, 35746],
 [35756, 35752, 35780, 35764, 35786, 35782, 35804, 35794, 35830, 35818],
 [35850, 35842, 35858, 35882, 35872, 35892, 35916, 35902, 35922, 35926],
 [35940, 35934, 35956, 35952, 35982, 35972, 36006, 35996, 36012, 36010],
 [36022, 36016, 36040, 36026, 36068, 36054, 36078, 36070, 36100, 36094],
 [36108, 36106, 36124, 36122, 36150, 36140, 36156, 36152, 36158, 36182],
 [36174, 36184, 36200, 36186, 36214, 36228, 36252, 36244, 36280, 36268],
 [36294, 36292, 36300, 36296, 36320, 36314, 36344, 36336, 36368, 36354],
 [36384, 36376, 36400, 36396, 36412, 36402, 40338, 40322, 40352, 40350],
 [40368, 40358, 40384, 40370, 40400, 40386, 40408, 40426, 40412, 40434],
 [40432, 40454, 40450, 40470, 40462, 40484, 40472, 40498, 40486, 40500],
 [40520, 40504, 40546, 40532, 40572, 40562, 40582, 40580, 40586, 40606],
 [40592, 40620, 40614, 40648, 40632, 40662, 40660, 40688, 40678, 40712],
 [40700, 40722, 40718, 40726, 40738, 40728, 40748, 40742, 40760, 40752],
 [40768, 40766, 40794, 40778, 40796, 40802, 40816, 40810, 40824, 40822],
 [40840, 40848, 40842, 40868, 40862, 40876, 40894, 40892, 40910, 40904],
 [40936, 40920, 40940, 40946, 40960, 40980, 40964, 40994, 41008, 41022],
 [41036, 41028, 41048, 41044, 41058, 41088, 41074, 41092, 41090, 41110],
 [41102, 41116, 41118, 41126, 41150, 41138, 41168, 41162, 41186, 41170],
 [41194, 41190, 41218, 41206, 41220, 41236, 41224, 41244, 41248, 41270],
 [41264, 41280, 41278, 41292, 41290, 41306, 41302, 41336, 41320, 41346],
 [41340, 41362, 41348, 41382, 41378, 41386, 41394, 41404, 41418, 41410],
 [41436, 41428, 41464, 41448, 41480, 41476, 41512, 41496, 41524, 41520],
 [41534, 41526, 41554, 41538, 41568, 41562, 41580, 41586, 41598, 41608],
 [41626, 41612, 41634, 41658, 41646, 41672, 41670, 41698, 41682, 41706],
 [41702, 41732, 41722, 41748, 41740, 41764, 41760, 41770, 41766, 41798],
 [41782, 41816, 41814, 41826, 41824, 41846, 41834, 41864, 41852, 41878],
 [41894, 41912, 41908, 41926, 41930, 41938, 41932, 41940, 41954, 41946],
 [41962, 41956, 41976, 41978, 41996, 41986, 42002, 42010, 42004, 42030],
 [42014, 42038, 42046, 42070, 42062, 42076, 42090, 42080, 42096, 42118],
 [42106, 42136, 42120, 42142, 42164, 42148, 42182, 42176, 42190, 42186],
 [42212, 42200, 42232, 42220, 42236, 42252, 42274, 42258, 42278, 42294],
 [42324, 42310, 42338, 42354, 42366, 42360, 42376, 42406, 42392, 42416],
 [42428, 42438, 42434, 42462, 42448, 42478, 42476, 42500, 42492, 42508],
 [42524, 42520, 42546, 42530, 42570, 42562, 42584, 42580, 42600, 42594],
 [42616, 42602, 42642, 42630, 42666, 42656, 42690, 42674, 42718, 42706],
 [42738, 42734, 42754, 42742, 42778, 42770, 42798, 42792, 42808, 42806],
 [42834, 42818, 42840, 42848, 42854, 42870, 42898, 42886, 42928, 42912],
 [42936, 42946, 42954, 42958, 42964, 42984, 42980, 43000, 43010, 43018],
 [43016, 43022, 43030, 43024, 43042, 43052, 43048, 43064, 43056, 43076],
 [43090, 43086, 43102, 43114, 43124, 43126, 43148, 43140, 43166, 43154],
 [43170, 43180, 43196, 43202, 43218, 43204, 43234, 43244, 43242, 43254],
 [43250, 43280, 43264, 43300, 43290, 43328, 43316, 43340, 43352, 43358],
 [43386, 43374, 43412, 43398, 43420, 43424, 43426, 43456, 43442, 43464],
 [43458, 43472, 43476, 43484, 43508, 43494, 43534, 43518, 43550, 43546],
 [43560, 43570, 43582, 43592, 43600, 43608, 43630, 43620, 43658, 43642],
 [43676, 43660, 43680, 43678, 43690, 43682, 43714, 43700, 43734, 43722],
 [43744, 43736, 43762, 43748, 43772, 43786, 43778, 43790, 43788, 43802],
 [43820, 43806, 43852, 43836, 43868, 43866, 43886, 43872, 43910, 43898],
 [43928, 43916, 43954, 43942, 43968, 43980, 43990, 43994, 44020, 44004],
 [44024, 44052, 44040, 44074, 44060, 44078, 44094, 44098, 44104, 44118],
 [44132, 44142, 44148, 44156, 44168, 44174, 44186, 44204, 44202, 44226],
 [44210, 44242, 44238, 44250, 44266, 44252, 44282, 44292, 44304, 44294],
 [44316, 44306, 44332, 44338, 44348, 44356, 44370, 44358, 44378, 44392],
 [44418, 44402, 44422, 44452, 44436, 44466, 44468, 44476, 44472, 44486],
 [44494, 44500, 44498, 44530, 44516, 44546, 44562, 44588, 44572, 44616],
 [44600, 44632, 44646, 44640, 44658, 44656, 44672, 44686, 44700, 44712],
 [44728, 44742, 44756, 44760, 44762, 44764, 44776, 44766, 44790, 44778],
 [44808, 44806, 44826, 44812, 44834, 44830, 44848, 44880, 44864, 44886],
 [44882, 44906, 44900, 44916, 44912, 44938, 44928, 44954, 44948, 44968],
 [44958, 44996, 44984, 45026, 45012, 45036, 45040, 45042, 45044, 45050],
 [45056, 45064, 45074, 45080, 45096, 45102, 45112, 45128, 45144, 45156],
 [45164, 45168, 45172, 45178, 45192, 45202, 45210, 45212, 45228, 45244],
 [45258, 45248, 45268, 45274, 45282, 45292, 45302, 45304, 45308, 45324],
 [45328, 45332, 45336, 45352, 45360, 45374, 45372, 45376, 45386, 45388],
 [45396, 45400, 45412, 45424, 45420, 45426, 45432, 45446, 45452, 45474],
 [45460, 45478, 45482, 45484, 45488, 45492, 45504, 45516, 45506, 45520],
 [45534, 45538, 45548, 45560, 45588, 45572, 45592, 45602, 45610, 45614],
 [45622, 45634, 45648, 45636, 45654, 45656, 45672, 45682, 45698, 45722],
 [45706, 45732, 45734, 45746, 45756, 45786, 45772, 45800, 45814, 45820],
 [45832, 45840, 45844, 45850, 45864, 45890, 45878, 45904, 45912, 45920],
 [45928, 45930, 45936, 45932, 45950, 45960, 45968, 45976, 45992, 46006],
 [46022, 46038, 46054, 46056, 46060, 46074, 46088, 46100, 46112, 46128],
 [46132, 46140, 46136, 46148, 46162, 46176, 46190, 46200, 46198, 46210],
 [46214, 46218, 46232, 46244, 46258, 46278, 46264, 46292, 46294, 46306],
 [46322, 46344, 46338, 46354, 46368, 46370, 46386, 46392, 46408, 46424],
 [46418, 46428, 46436, 46444, 46452, 46462, 46482, 46476, 46492, 46504],
 [46516, 46530, 46540, 46550, 46560, 46564, 46568, 46584, 46600, 46610],
 [46624, 46632, 46640, 46642, 46656, 46652, 46662, 46678, 46684, 46688],
 [46710, 46696, 46720, 46728, 46738, 46752, 46758, 46774, 46782, 46804],
 [46796, 46818, 46830, 46842, 46848, 46864, 46890, 46876, 46906, 46908],
 [46924, 46930, 46946, 46956, 46964, 46976, 46972, 46990, 46998, 47030],
 [47014, 47036, 47034, 47044, 47056, 47062, 47070, 47078, 47090, 47102],
 [47122, 47116, 47126, 47142, 47152, 47160, 47172, 47174, 47182, 47186],
 [47194, 47196, 47212, 47226, 47232, 47258, 47242, 47268, 47278, 47286],
 [47288, 47294, 47308, 47312, 47310, 47316, 47324, 47332, 47340, 47352],
 [47362, 47370, 47368, 47382, 47396, 47410, 47416, 47418, 47422, 47430],
 [47432, 47440, 47454, 47456, 47460, 47466, 47480, 47496, 47494, 47508],
 [47522, 47534, 47548, 47550, 47552, 47558, 47568, 47574, 47584, 47580],
 [47594, 47596, 47602, 47606, 47608, 47628, 47614, 47634, 47642, 47654],
 [47668, 47682, 47696, 47710, 47724, 47712, 47728, 47744, 47748, 47764],
 [47772, 47786, 47792, 47802, 47800, 47810, 47814, 47820, 47828, 47830],
 [47838, 47858, 47848, 47866, 47868, 47872, 47876, 47884, 47900, 47898],
 [47902, 47918, 47924, 47932, 47936, 47954, 47944, 47962, 47976, 47978],
 [47992, 48008, 47996, 48014, 48024, 48026, 48032, 48048, 48044, 48050],
 [48066, 48070, 48074, 48090, 48094, 48096, 48098, 48112, 48116, 48132],
 [48148, 48140, 48154, 48168, 48172, 48188, 48190, 48196, 48202, 48214],
 [48230, 48236, 48246, 48252, 48268, 48282, 48298, 48308, 48320, 48330],
 [48338, 48350, 48360, 48354, 48364, 48372, 48376, 48390, 48400, 48410],
 [48416, 48412, 48424, 48434, 48436, 48442, 48456, 48458, 48460, 48472],
 [48478, 48502, 48490, 48514, 48516, 48532, 48536, 48546, 48554, 48560],
 [48562, 48576, 48588, 48604, 48618, 48626, 48628, 48636, 48652, 48668],
 [48678, 48694, 48708, 48714, 48724, 48746, 48732, 48762, 48770, 48776],
 [48786, 48796, 48808, 48812, 48824, 48840, 48866, 48850, 48878, 48882],
 [48884, 48890, 48896, 48904, 48916, 48932, 48944, 48960, 48970, 48974],
 [48996, 48982, 49000, 49008, 50232, 50238, 50244, 50260, 50262, 50264],
 [50272, 50280, 50282, 50296, 50312, 50318, 50334, 50348, 50350, 50358],
 [50374, 50382, 50402, 50396, 50412, 50422, 50428, 50436, 50440, 50452],
 [50468, 50464, 50472, 50478, 50492, 50496, 50512, 50514, 50528, 50544],
 [50570, 50560, 50578, 50586, 50602, 50612, 50618, 50630, 50626, 50646],
 [50658, 50666, 50676, 50684, 50688, 50700, 50728, 50716, 50732, 50734],
 [50744, 50750, 50754, 50776, 50760, 50792, 50806, 50814, 50830, 50846],
 [50858, 50868, 50882, 50908, 50894, 50910, 50926, 50932, 50938, 50956],
 [50944, 50966, 50974, 50990, 51004, 51018, 51030, 51036, 51042, 51038],
 [51052, 51054, 51066, 51078, 51080, 51082, 51096, 51106, 51112, 51128],
 [51140, 51150, 51160, 51164, 51176, 51188, 51192, 51208, 51210, 51236],
 [51224, 51248, 51258, 51260, 51266, 51268, 51272, 51280, 51294, 51306],
 [51314, 51330, 51336, 51350, 51358, 51364, 51374, 51376, 51382, 51394],
 [51404, 51402, 51410, 51418, 51428, 51442, 51450, 51466, 51486, 51480],
 [51498, 51512, 51516, 51530, 51538, 51544, 51548, 51562, 51574, 51564],
 [51578, 51586, 51596, 51598, 51602, 51604, 51630, 51620, 51632, 51648],
 [51658, 51664, 51670, 51674, 51690, 51684, 51700, 51702, 51712, 51724],
 [51730, 51744, 51760, 51752, 51762, 51772, 51784, 51794, 51808, 51820],
 [51836, 51856, 51850, 51864, 51872, 51888, 51890, 51906, 51912, 51936],
 [51920, 51944, 51948, 51964, 51980, 51992, 52008, 52018, 52036, 52024],
 [52040, 52054, 52070, 52080, 52086, 52090, 52100, 52110, 52122, 52140],
 [52138, 52148, 52154, 52162, 52178, 52186, 52206, 52196, 52210, 52214],
 [52228, 52244, 52250, 52260, 52270, 52286, 52300, 52312, 52318, 52334],
 [52342, 52336, 52346, 52348, 52364, 52378, 52398, 52390, 52410, 52414],
 [52424, 52440, 52448, 52450, 52464, 52468, 52476, 52488, 52498, 52510],
 [52512, 52542, 52528, 52554, 52570, 52578, 52586, 52602, 52614, 52620],
 [52634, 52650, 52638, 52658, 52666, 52680, 52692, 52708, 52734, 52718],
 [52742, 52748, 52760, 52772, 52774, 52790, 52792, 52802, 52800, 52814],
 [52828, 52834, 52842, 52858, 52866, 52874, 52876, 52888, 52880, 52902],
 [52916, 52928, 52944, 52950, 52958, 52976, 52972, 52992, 52998, 53014],
 [53030, 53038, 53052, 53062, 53072, 53080, 53096, 53110, 53118, 53120],
 [53130, 53136, 53138, 53140, 53150, 53160, 53176, 53188, 53198, 53216],
 [53212, 53224, 53238, 53246, 53256, 53266, 53268, 53272, 53282, 53286],
 [53290, 53300, 53304, 53320, 53324, 53338, 53358, 53346, 53372, 53374],
 [53382, 53388, 53400, 53410, 53426, 53420, 53438, 53440, 53442, 53450],
 [53460, 53464, 53470, 53486, 53494, 53500, 53508, 53514, 53524, 53538],
 [53554, 53556, 53572, 53578, 53586, 53598, 53604, 53610, 53622, 53626],
 [53636, 53642, 53646, 53656, 53672, 53682, 53688, 53700, 53710, 53724],
 [53740, 53752, 53768, 53770, 53776, 53780, 53792, 53818, 53808, 53832],
 [53840, 53854, 53858, 53866, 53874, 53880, 53884, 53892, 53886, 53902],
 [53914, 53922, 53930, 53932, 53942, 53938, 53944, 53948, 53962, 53970],
 [53992, 53984, 54008, 54018, 54020, 54034, 54044, 54060, 54080, 54064],
 [54082, 54096, 54106, 54114, 54136, 54120, 54142, 54158, 54162, 54166],
 [54170, 54184, 54200, 54210, 54226, 54218, 54228, 54242, 54256, 54260],
 [54270, 54286, 54288, 54300, 54308, 54322, 54336, 54346, 54358, 54366],
 [54372, 54388, 54402, 54416, 54428, 54440, 54442, 54452, 54460, 54462],
 [54470, 54480, 54488, 54494, 54496, 54498, 54502, 54512, 54514, 54526],
 [54538, 54536, 54542, 54554, 54570, 54586, 54592, 54600, 54608, 54610],
 [54616, 54626, 54632, 54636, 54644, 54646, 54652, 54654, 54658, 54664],
 [54668, 54678, 54680, 54682, 54702, 54688, 54718, 54722, 54738, 54748],
 [54758, 54774, 54784, 54780, 54800, 54812, 54816, 54820, 54834, 54838],
 [54836, 54844, 54854, 54858, 54872, 54900, 54884, 54902, 54908, 54922],
 [54938, 54954, 54956, 54962, 54970, 54974, 54976, 54988, 54990, 55000],
 [55002, 55016, 55022, 55030, 55046, 55060, 55076, 55088, 55092, 55100],
 [55116, 55122, 55136, 55148, 55158, 55162, 55170, 55182, 55196, 55210],
 [55220, 55228, 55232, 55244, 55264, 55256, 55266, 55276, 55290, 55302],
 [55318, 55336, 55328, 55346, 55360, 55366, 55378, 55380, 55390, 55402],
 [55418, 55406, 55432, 55438, 55454, 55458, 55468, 55474, 55488, 55502],
 [55524, 55510, 55540, 55556, 55566, 55568, 55584, 55586, 55604, 55602],
 [55618, 55634, 55636, 55644, 55654, 55666, 55674, 55678, 55694, 55704],
 [55700, 55706, 55710, 55722, 55728, 55740, 55756, 55774, 55772, 55776],
 [55778, 55782, 55792, 55794, 55806, 55820, 55830, 55840, 55852, 55862],
 [55864, 55868, 55882, 55890, 55892, 55908, 55914, 55924, 55926, 55938],
 [55952, 55968, 55974, 55980, 55986, 55984, 56002, 56016, 56030, 56044],
 [56060, 56062, 56066, 56076, 56084, 56096, 56098, 56100, 56112, 56130],
 [56126, 56148, 56146, 56170, 56156, 56184, 56178, 56188, 56194, 56202],
 [56232, 56216, 56242, 56240, 56258, 56266, 56268, 56276, 56278, 56286],
 [56300, 56316, 56324, 56336, 56350, 56356, 56362, 56376, 56388, 56394],
 [56400, 56412, 56418, 56424, 56434, 56440, 56442, 56458, 56474, 56490],
 [56520, 56506, 56532, 56544, 56560, 56562, 56570, 56574, 56590, 56606],
 [56624, 56610, 56628, 56644, 56670, 56656, 56682, 56696, 56704, 56716],
 [56720, 56734, 56744, 56756, 56762, 56768, 56772, 56784, 56796, 56802],
 [56810, 56816, 56826, 56840, 56844, 56858, 56868, 56872, 56880, 56894],
 [56888, 56902, 56904, 56910, 56920, 56928, 56940, 56950, 56960, 56970],
 [56978, 56984, 56998, 57006, 57012, 57022, 57024, 57036, 57038, 57042],
 [57040, 57054, 57068, 57074, 57086, 57100, 57116, 57124, 57122, 57128],
 [57132, 57146, 57162, 57166, 57172, 57184, 57198, 57214, 57218, 57224],
 [57230, 57244, 57252, 57246, 57256, 57262, 57278, 57282, 57290, 57318],
 [57302, 57322, 57332, 57348, 57360, 57366, 57380, 57388, 57394, 57392],
 [57396, 57408, 57422, 57424, 57438, 57444, 57456, 57476, 57472, 57484],
 [57498, 57510, 57522, 57536, 57550, 57540, 57556, 57564, 57576, 57582],
 [57594, 57596, 57604, 57612, 57628, 57644, 57660, 57670, 57682, 57696],
 [57708, 57700, 57716, 57732, 57736, 57742, 57756, 57764, 57770, 57784],
 [57792, 57806, 57794, 57822, 57832, 57844, 57860, 57874, 57890, 57910],
 [57898, 57940, 57926, 57944, 57946, 57952, 57962, 57972, 58004, 57988],
 [58016, 58026, 58032, 58042, 58058, 58052, 58072, 58088, 58102, 58114],
 [58132, 58124, 58138, 58154, 58164, 58166, 58176, 58184, 58198, 58212],
 [58220, 58234, 58232, 58250, 58242, 58260, 58270, 58280, 58288, 58298],
 [58304, 58318, 58322, 58330, 58342, 58346, 58358, 58360, 58366, 58376],
 [58388, 58390, 58396, 58402, 58416, 58432, 58460, 58446, 58470, 58472],
 [58480, 58496, 58504, 58498, 58514, 58522, 58526, 58542, 58566, 58554],
 [58580, 58590, 58606, 58616, 58622, 58628, 58634, 58638, 58642, 58654],
 [58644, 58660, 58664, 58672, 58684, 58688, 58698, 58708, 58710, 58714],
 [58736, 58726, 58738, 58746, 58752, 58760, 58774, 58800, 58786, 58804],
 [58820, 58830, 58836, 58852, 58842, 58858, 58872, 58878, 58892, 58906],
 [58914, 58908, 58918, 58928, 58942, 58958, 58984, 58974, 58992, 59006],
 [59022, 59034, 59040, 59054, 59042, 59060, 59072, 59088, 59096, 59100],
 [59116, 59126, 59134, 59138, 59154, 59168, 59190, 59184, 59206, 59214],
 [59218, 59236, 59224, 59250, 59260, 59276, 59278, 59290, 59306, 59292],
 [59320, 59322, 59332, 59338, 59340, 59342, 59350, 59364, 59374, 59398],
 [59388, 59404, 59418, 59430, 59446, 59468, 59456, 59470, 59482, 59486],
 [59500, 59496, 59502, 59504, 59520, 59534, 59548, 59558, 59572, 59582],
 [59588, 59616, 59604, 59626, 59634, 59650, 59654, 59686, 59670, 59696],
 [59708, 59714, 59724, 59734, 59728, 59748, 59752, 59754, 59764, 59776],
 [59782, 59796, 59810, 59818, 59822, 59828, 59840, 59854, 59866, 59872],
 [59874, 59894, 59890, 59910, 59924, 59928, 59944, 59934, 59950, 59962],
 [59978, 59984, 59992, 59994, 60012, 60002, 60028, 60044, 60056, 60062],
 [60078, 60080, 60082, 60096, 60100, 60116, 60130, 60142, 60152, 60166],
 [35552, 35536, 35566, 35568, 35572, 35586, 35590, 35606, 35612, 35622],
 [35628, 35636, 35648, 35640, 35650, 35658, 35666, 35680, 35690, 35692],
 [35698, 35714, 35730, 35742, 35750, 35764, 35774, 35788, 35802, 35830],
 [35818, 35838, 35850, 35860, 35876, 35882, 35886, 35902, 35894, 35910],
 [35924, 35930, 35936, 35940, 35950, 35964, 35974, 35982, 35988, 36000],
 [36022, 36012, 36026, 36040, 36046, 36058, 36064, 36066, 36068, 36082],
 [36100, 36094, 36106, 36122, 36130, 36144, 36146, 36158, 36174, 36178],
 [36194, 36212, 36208, 36224, 36238, 36242, 36258, 36270, 36290, 36280],
 [36298, 36302, 36304, 36306, 36322, 36324, 36330, 36336, 36340, 36352],
 [36362, 36376, 36382, 36396, 36406, 36422, 36432, 36444, 36452, 36458],
 [36474, 36480, 36492, 36502, 36518, 36522, 36524, 36526, 36534, 36550],
 [36552, 36560, 36564, 36568, 36578, 36586, 36598, 36604, 36608, 36616],
 [36628, 36636, 36640, 36648, 36656, 36664, 36658, 36666, 36670, 36690],
 [36678, 36694, 36700, 36702, 36718, 36724, 36734, 36746, 36756, 36768],
 [36782, 36786, 36796, 36798, 36808, 36822, 36818, 36832, 36844, 36854],
 [36868, 36878, 36894, 36898, 36922, 36912, 36926, 36940, 36954, 36964],
 [36980, 36988, 36990, 37004, 37014, 37018, 37030, 37038, 37050, 37054],
 [37086, 37070, 37104, 37098, 37106, 37114, 37122, 37138, 37154, 37156],
 [37168, 37176, 37180, 37196, 37212, 37216, 37232, 37244, 37248, 37260],
 [37274, 37288, 37296, 37302, 37310, 37330, 37316, 37346, 37358, 37374],

In [3]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, fpmax, fpgrowth

te = TransactionEncoder()
te_ary = te.fit(ports_matrix).transform(ports_matrix)
df = pd.DataFrame(te_ary, columns=te.columns_)

df

,32768,32774,32784,32788,32792,32798,32802,32812,32814,32822,...,60938,60944,60948,60956,60962,60966,60978,60982,60984,60992
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4926,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4927,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4928,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4929,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4930,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [5]:
# frequent_itemsets = fpgrowth(df, min_support=0.3, use_colnames=True)
frequent_itemsets = fpgrowth(df, min_support=0.1, use_colnames=True)
### alternatively:
#frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
#frequent_itemsets = fpmax(df, min_support=0.6, use_colnames=True)

frequent_itemsets.head(20)

     support itemsets
0   0.109308  (35262)
1   0.152910  (35340)
2   0.149463  (35320)
3   0.137497  (35310)
4   0.128777  (35200)
5   0.127966  (35184)
6   0.145204  (35292)
7   0.128574  (35256)
8   0.141351  (35174)
9   0.170148  (35202)
10  0.151085  (35252)
11  0.147232  (35244)
12  0.137092  (35212)
13  0.135267  (35228)
14  0.122288  (35236)
15  0.120057  (35226)
16  0.171568  (35288)
17  0.160211  (35306)
18  0.156155  (35278)
19  0.135267  (35360)

In [10]:
import psycopg2

conn = psycopg2.connect(database="web_honeypot_generated", user = "postgres", password = "admin", host = "127.0.0.1", port = "5432")

print("Opened database successfully")

Opened database successfully

In [11]:
# create table
cur = conn.cursor()
cur.execute('''CREATE TABLE assoc_rules_ports (
            ID INT PRIMARY KEY     NOT NULL,
            SUPPORT           REAL    NOT NULL,
            PORT            VARCHAR(255)     NOT NULL);''')

print("Table created successfully")

conn.commit()

Table created successfully

In [12]:
# insert data

cur = conn.cursor()

insert_query = """
    INSERT INTO assoc_rules_ports (ID, SUPPORT, PORT)
    VALUES (%s, %s, %s)
"""

for idx, row in frequent_itemsets.iterrows():
    cur.execute(
        insert_query,
        (int(idx), float(row["support"]), str(list(row["itemsets"])))
    )

conn.commit()
print("Records created successfully")
conn.close()

Records created successfully